crusher changes sept19
E3SM-Project/EKAT pull request #257
Opened 2022-10-14 16:42 UTC by oksanaguba

2022-10-14 16:55 UTC, E3SM-Autotester commented
Status Flag 'Pre-Test Inspection' - Auto Inspected - Inspection Is Not Necessary for this Pull Request.

2022-10-14 16:56 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: EKAT_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 351</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>EKAT_SOURCE_BRANCH</td>
    <td>oksanaguba/crusher-changes-sept19</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_SHA</td>
    <td>c05f7b99a48143a106085c0e6353f9eb0b6d66fe</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_SHA</td>
    <td>1052776a2ee5cef2607515453124a0d7f007bf4d</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>257</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>EKAT</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: EKAT_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 448</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>EKAT_SOURCE_BRANCH</td>
    <td>oksanaguba/crusher-changes-sept19</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_SHA</td>
    <td>c05f7b99a48143a106085c0e6353f9eb0b6d66fe</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_SHA</td>
    <td>1052776a2ee5cef2607515453124a0d7f007bf4d</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>257</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>EKAT</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: EKAT_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 465</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>EKAT_SOURCE_BRANCH</td>
    <td>oksanaguba/crusher-changes-sept19</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_SHA</td>
    <td>c05f7b99a48143a106085c0e6353f9eb0b6d66fe</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_SHA</td>
    <td>1052776a2ee5cef2607515453124a0d7f007bf4d</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>257</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>EKAT</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: EKAT (E3SM-Project/EKAT)</dt>
  <ul>
    <li>Branch: oksanaguba/crusher-changes-sept19</li>
    <li>SHA: c05f7b99a48143a106085c0e6353f9eb0b6d66fe</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

Pull Request Author: oksanaguba
</details>

2022-10-14 17:06 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: 1 or more Jobs FAILED

Note: Testing will normally be attempted again in approx. 4 Hrs. If a change to the PR source branch occurs, the testing will be attempted again on next available autotester run.

<details>
<summary>
  <b>Pull Request Auto Testing has FAILED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: EKAT_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 351</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>EKAT_SOURCE_BRANCH</td>
    <td>oksanaguba/crusher-changes-sept19</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_SHA</td>
    <td>c05f7b99a48143a106085c0e6353f9eb0b6d66fe</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_SHA</td>
    <td>1052776a2ee5cef2607515453124a0d7f007bf4d</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>257</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>EKAT</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: EKAT_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 448</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>EKAT_SOURCE_BRANCH</td>
    <td>oksanaguba/crusher-changes-sept19</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_SHA</td>
    <td>c05f7b99a48143a106085c0e6353f9eb0b6d66fe</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_SHA</td>
    <td>1052776a2ee5cef2607515453124a0d7f007bf4d</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>257</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>EKAT</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: EKAT_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 465</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>EKAT_SOURCE_BRANCH</td>
    <td>oksanaguba/crusher-changes-sept19</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_SHA</td>
    <td>c05f7b99a48143a106085c0e6353f9eb0b6d66fe</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_SHA</td>
    <td>1052776a2ee5cef2607515453124a0d7f007bf4d</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>257</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>EKAT</td>
  </tr>
</table>
</details>


<details>
<summary>
  <b>Console Output (last 100K lines) : EKAT_PullRequest_Autotester_Mappy # 351</b> (click to expand)
</summary>
<pre>
<code>
Running as SYSTEM
Building remotely on mappy in workspace /ascldap/users/e3sm-jenkins/jenkins-ws/workspace/EKAT_PullRequest_Autotester_Mappy
The recommended git tool is: NONE
using credential cf1815d3-62c3-4157-a38d-0ad235093618
Wiping out workspace first.
Cloning the remote Git repository
Honoring refspec on initial clone
Cloning repository https://github.com/E3SM-Project/EKAT.git
 > git init /ascldap/users/e3sm-jenkins/jenkins-ws/workspace/EKAT_PullRequest_Autotester_Mappy/351/ekat-src # timeout=10
Fetching upstream changes from https://github.com/E3SM-Project/EKAT.git
 > git --version # timeout=10
 > git --version # 'git version 1.8.3.1'
using GIT_SSH to set credentials jgfouca github key
Setting http proxy: proxy.sandia.gov:80
 > git fetch --tags --progress https://github.com/E3SM-Project/EKAT.git +refs/heads/master:refs/remotes/origin/master +refs/pull/257/head:refs/heads/pr/257 # timeout=10
 > git config remote.origin.url https://github.com/E3SM-Project/EKAT.git # timeout=10
 > git config --add remote.origin.fetch +refs/heads/master:refs/remotes/origin/master # timeout=10
 > git config --add remote.origin.fetch +refs/pull/257/head:refs/heads/pr/257 # timeout=10
Avoid second fetch
 > git rev-parse refs/remotes/origin/pr/257^{commit} # timeout=10
 > git rev-parse pr/257^{commit} # timeout=10
JENKINS-19022: warning: possible memory leak due to Git plugin usage; see: https://plugins.jenkins.io/git/#remove-git-plugin-buildsbybranch-builddata-script
Checking out Revision c05f7b99a48143a106085c0e6353f9eb0b6d66fe (pr/257)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f c05f7b99a48143a106085c0e6353f9eb0b6d66fe # timeout=10
Commit message: "fix comments"
First time build. Skipping changelog.
 > git remote # timeout=10
 > git submodule init # timeout=10
 > git submodule sync # timeout=10
 > git config --get remote.origin.url # timeout=10
 > git submodule init # timeout=10
 > git config -f .gitmodules --get-regexp ^submodule\.(.+)\.url # timeout=10
 > git config --get submodule.extern/kokkos.url # timeout=10
 > git remote # timeout=10
 > git config --get remote.origin.url # timeout=10
 > git config -f .gitmodules --get submodule.extern/kokkos.path # timeout=10
 > git config --get submodule.extern/yaml-cpp.url # timeout=10
 > git remote # timeout=10
 > git config --get remote.origin.url # timeout=10
 > git config -f .gitmodules --get submodule.extern/yaml-cpp.path # timeout=10
 > git config --get submodule.extern/spdlog.url # timeout=10
 > git remote # timeout=10
 > git config --get remote.origin.url # timeout=10
 > git config -f .gitmodules --get submodule.extern/spdlog.path # timeout=10
 > git config --get submodule.extern/Catch2.url # timeout=10
 > git remote # timeout=10
 > git config --get remote.origin.url # timeout=10
 > git config -f .gitmodules --get submodule.extern/Catch2.path # timeout=10
using GIT_SSH to set credentials jgfouca github key
 > git submodule update --init --recursive extern/kokkos # timeout=5
hudson.plugins.git.GitException: Command "git submodule update --init --recursive extern/kokkos" returned status code 1:
stdout: Cloning into 'extern/kokkos'...

stderr: fatal: reference is not a tree: 24b3eb42ba72cc4ea4dae441916dd6db8dcb8613
Unable to checkout '24b3eb42ba72cc4ea4dae441916dd6db8dcb8613' in submodule path 'extern/kokkos'

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2675)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:2099)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$500(CliGitAPIImpl.java:85)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$7.lambda$execute$0(CliGitAPIImpl.java:1506)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:74)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutorService.execute(MoreExecutors.java:323)
	at java.util.concurrent.ExecutorCompletionService.submit(ExecutorCompletionService.java:181)
	at org.jenkinsci.plugins.gitclient.cgit.GitCommandsExecutor.submitRemainingCommand(GitCommandsExecutor.java:98)
	at org.jenkinsci.plugins.gitclient.cgit.Gi [...]

2022-10-14 17:35 UTC, bartgol requested changes
I think the version of kokkos you are using does not include stuff that we need in e3sm. You should branch off of origin/kokkos-3.6-with-clang-fix (what's currently used in ekat master), and merge the upstream kokkos version you need into your branch.

2022-10-14 18:17 UTC, oksanaguba commented
@bartgol i am not sure what you mean. are we talking about ekat kokkos? then this branch points to June 10th commit (roughly needed for hip), while scream master version of ekat kokkos is from Feb 24, too old.

2022-10-14 21:01 UTC, bartgol commented
> @bartgol i am not sure what you mean. are we talking about ekat kokkos? then this branch points to June 10th commit (roughly needed for hip), while scream master version of ekat kokkos is from Feb 24, too old.

I'm looking at the version of kokkos in ekat's master, and see a lot of commits that are not in the version of kokkos in your branch. For instance, this are the last few commits in the current master's kokkos version:

```
* 569fa3ac8 - (8 months ago) Disambiguate fujitsu-clang and clang compilers - Azamat Mametjanov (HEAD, origin/kokkos-3.6-with-clang-fix)
*   b52f8c835 - (6 months ago) Merge pull request #4827 from ndellingwood/release-3.6.00 - Christian Trott (tag: 3.6.00)
|\  
| * f2a05d316 - (6 months ago) Update master_history for Kokkos 3.6.00 - Nathan Ellingwood
| * 6ea708ffd - (6 months ago) Merge pull request #4967 from ndellingwood/rc-3.6.0-cherrypick-4966 - Damien L-G
| * faa8937ea - (6 months ago) Merge pull request #4944 from ndellingwood/rc-3.6.0-cherrypick-4943 - Damien L-G
| * 0a9e3b6eb - (6 months ago) Merge pull request #4934 from Rombur/fix_deep_copy_2 - Christian Trott
| * 66217f206 - (7 months ago) Update master_history for Kokkos 3.6.00 - Nathan Ellingwood
| * 1e9132944 - (7 months ago) Merge pull request #4866 from ndellingwood/rc-3.6.0-4852 - Christian Trott
| * 6b8493786 - (7 months ago) Merge pull request #4869 from crtrott/fix-scratch-locks - Christian Trott
| * 133de5679 - (7 months ago) Merge pull request #4851 from ndellingwood/rc-3.6.0-cherrypick-4841 - Damien L-G
| * 32736d35d - (7 months ago) Merge pull request #4865 from Rombur/fix_4850 - Christian Trott
| * 44e1b8487 - (8 months ago) Merge pull request #4830 from ndellingwood/rc-3.6.0-pthreadfix - Christian Trott
| * 2478f3b96 - (8 months ago) Merge branch 'release-candidate-3.6.0' for 3.6.00 - Nathan Ellingwood
|/| 
| *   c838bdcf4 - (8 months ago) Merge pull request #4807 from ndellingwood/rc-3.6.0-changelog - Damien L-G
```
Most of these are not in the version of kokkos in your branch, and I'm worried we might be messing up something here. Also, besides all the commits from the kokkos devs, we also want to keep the last commit, by Azamat, which fixes something that caused issues with our sems modules.

What I was suggesting is to create a new branch off of `569fa3ac8` (current version in ekat/master), and merge in whatever branch you are using from the upstream kokkos repo.

Also, if you want to upgrade kokkos, I would recommend to stick with their releases, rather than a random commit half way through. I would prefer picking their 3.7.00 tag. I checked the history of that tag, and it includes the last few commits of the version you are using.

2022-10-14 21:23 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: EKAT_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 352</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>EKAT_SOURCE_BRANCH</td>
    <td>oksanaguba/crusher-changes-sept19</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_SHA</td>
    <td>c05f7b99a48143a106085c0e6353f9eb0b6d66fe</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_SHA</td>
    <td>1052776a2ee5cef2607515453124a0d7f007bf4d</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>257</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>EKAT</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: EKAT_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 449</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>EKAT_SOURCE_BRANCH</td>
    <td>oksanaguba/crusher-changes-sept19</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_SHA</td>
    <td>c05f7b99a48143a106085c0e6353f9eb0b6d66fe</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_SHA</td>
    <td>1052776a2ee5cef2607515453124a0d7f007bf4d</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>257</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>EKAT</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: EKAT_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 466</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>EKAT_SOURCE_BRANCH</td>
    <td>oksanaguba/crusher-changes-sept19</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_SHA</td>
    <td>c05f7b99a48143a106085c0e6353f9eb0b6d66fe</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_SHA</td>
    <td>1052776a2ee5cef2607515453124a0d7f007bf4d</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>257</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>EKAT</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: EKAT (E3SM-Project/EKAT)</dt>
  <ul>
    <li>Branch: oksanaguba/crusher-changes-sept19</li>
    <li>SHA: c05f7b99a48143a106085c0e6353f9eb0b6d66fe</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

Pull Request Author: oksanaguba
</details>

2022-10-14 21:33 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: 1 or more Jobs FAILED

Note: Testing will normally be attempted again in approx. 4 Hrs. If a change to the PR source branch occurs, the testing will be attempted again on next available autotester run.

<details>
<summary>
  <b>Pull Request Auto Testing has FAILED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: EKAT_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 352</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>EKAT_SOURCE_BRANCH</td>
    <td>oksanaguba/crusher-changes-sept19</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_SHA</td>
    <td>c05f7b99a48143a106085c0e6353f9eb0b6d66fe</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_SHA</td>
    <td>1052776a2ee5cef2607515453124a0d7f007bf4d</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>257</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>EKAT</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: EKAT_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 449</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>EKAT_SOURCE_BRANCH</td>
    <td>oksanaguba/crusher-changes-sept19</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_SHA</td>
    <td>c05f7b99a48143a106085c0e6353f9eb0b6d66fe</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_SHA</td>
    <td>1052776a2ee5cef2607515453124a0d7f007bf4d</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>257</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>EKAT</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: EKAT_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 466</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>EKAT_SOURCE_BRANCH</td>
    <td>oksanaguba/crusher-changes-sept19</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_SHA</td>
    <td>c05f7b99a48143a106085c0e6353f9eb0b6d66fe</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_SHA</td>
    <td>1052776a2ee5cef2607515453124a0d7f007bf4d</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>257</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>EKAT</td>
  </tr>
</table>
</details>


<details>
<summary>
  <b>Console Output (last 100K lines) : EKAT_PullRequest_Autotester_Mappy # 352</b> (click to expand)
</summary>
<pre>
<code>
Running as SYSTEM
Building remotely on mappy in workspace /ascldap/users/e3sm-jenkins/jenkins-ws/workspace/EKAT_PullRequest_Autotester_Mappy
The recommended git tool is: NONE
using credential cf1815d3-62c3-4157-a38d-0ad235093618
Wiping out workspace first.
Cloning the remote Git repository
Honoring refspec on initial clone
Cloning repository https://github.com/E3SM-Project/EKAT.git
 > git init /ascldap/users/e3sm-jenkins/jenkins-ws/workspace/EKAT_PullRequest_Autotester_Mappy/352/ekat-src # timeout=10
Fetching upstream changes from https://github.com/E3SM-Project/EKAT.git
 > git --version # timeout=10
 > git --version # 'git version 1.8.3.1'
using GIT_SSH to set credentials jgfouca github key
Setting http proxy: proxy.sandia.gov:80
 > git fetch --tags --progress https://github.com/E3SM-Project/EKAT.git +refs/heads/master:refs/remotes/origin/master +refs/pull/257/head:refs/heads/pr/257 # timeout=10
 > git config remote.origin.url https://github.com/E3SM-Project/EKAT.git # timeout=10
 > git config --add remote.origin.fetch +refs/heads/master:refs/remotes/origin/master # timeout=10
 > git config --add remote.origin.fetch +refs/pull/257/head:refs/heads/pr/257 # timeout=10
Avoid second fetch
 > git rev-parse refs/remotes/origin/pr/257^{commit} # timeout=10
 > git rev-parse pr/257^{commit} # timeout=10
JENKINS-19022: warning: possible memory leak due to Git plugin usage; see: https://plugins.jenkins.io/git/#remove-git-plugin-buildsbybranch-builddata-script
Checking out Revision c05f7b99a48143a106085c0e6353f9eb0b6d66fe (pr/257)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f c05f7b99a48143a106085c0e6353f9eb0b6d66fe # timeout=10
Commit message: "fix comments"
 > git rev-list --no-walk c05f7b99a48143a106085c0e6353f9eb0b6d66fe # timeout=10
 > git remote # timeout=10
 > git submodule init # timeout=10
 > git submodule sync # timeout=10
 > git config --get remote.origin.url # timeout=10
 > git submodule init # timeout=10
 > git config -f .gitmodules --get-regexp ^submodule\.(.+)\.url # timeout=10
 > git config --get submodule.extern/kokkos.url # timeout=10
 > git remote # timeout=10
 > git config --get remote.origin.url # timeout=10
 > git config -f .gitmodules --get submodule.extern/kokkos.path # timeout=10
 > git config --get submodule.extern/yaml-cpp.url # timeout=10
 > git remote # timeout=10
 > git config --get remote.origin.url # timeout=10
 > git config -f .gitmodules --get submodule.extern/yaml-cpp.path # timeout=10
 > git config --get submodule.extern/spdlog.url # timeout=10
 > git remote # timeout=10
 > git config --get remote.origin.url # timeout=10
 > git config -f .gitmodules --get submodule.extern/spdlog.path # timeout=10
 > git config --get submodule.extern/Catch2.url # timeout=10
 > git remote # timeout=10
 > git config --get remote.origin.url # timeout=10
 > git config -f .gitmodules --get submodule.extern/Catch2.path # timeout=10
using GIT_SSH to set credentials jgfouca github key
 > git submodule update --init --recursive extern/kokkos # timeout=5
hudson.plugins.git.GitException: Command "git submodule update --init --recursive extern/kokkos" returned status code 1:
stdout: Cloning into 'extern/kokkos'...

stderr: fatal: reference is not a tree: 24b3eb42ba72cc4ea4dae441916dd6db8dcb8613
Unable to checkout '24b3eb42ba72cc4ea4dae441916dd6db8dcb8613' in submodule path 'extern/kokkos'

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2675)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:2099)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$500(CliGitAPIImpl.java:85)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$7.lambda$execute$0(CliGitAPIImpl.java:1506)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:74)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutorService.execute(MoreExecutors.java:323)
	at java.util.concurrent.ExecutorCompletionService.submit(ExecutorCompletionService.java:181)
	at org.jenkinsci.plugins.gitclient.cgit.GitCommandsExecutor.submitRemainingCommand(GitCommandsExecutor.java:98)
	 [...]

2022-10-15 01:56 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: 1 or more Jobs FAILED

Note: Testing will normally be attempted again in approx. 4 Hrs. If a change to the PR source branch occurs, the testing will be attempted again on next available autotester run.

<details>
<summary>
  <b>Pull Request Auto Testing has FAILED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: EKAT_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 353</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>EKAT_SOURCE_BRANCH</td>
    <td>oksanaguba/crusher-changes-sept19</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_SHA</td>
    <td>c05f7b99a48143a106085c0e6353f9eb0b6d66fe</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_SHA</td>
    <td>1052776a2ee5cef2607515453124a0d7f007bf4d</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>257</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>EKAT</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: EKAT_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 450</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>EKAT_SOURCE_BRANCH</td>
    <td>oksanaguba/crusher-changes-sept19</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_SHA</td>
    <td>c05f7b99a48143a106085c0e6353f9eb0b6d66fe</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_SHA</td>
    <td>1052776a2ee5cef2607515453124a0d7f007bf4d</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>257</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>EKAT</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: EKAT_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 467</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>EKAT_SOURCE_BRANCH</td>
    <td>oksanaguba/crusher-changes-sept19</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_SHA</td>
    <td>c05f7b99a48143a106085c0e6353f9eb0b6d66fe</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_SHA</td>
    <td>1052776a2ee5cef2607515453124a0d7f007bf4d</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>257</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>EKAT</td>
  </tr>
</table>
</details>


<details>
<summary>
  <b>Console Output (last 100K lines) : EKAT_PullRequest_Autotester_Mappy # 353</b> (click to expand)
</summary>
<pre>
<code>
Running as SYSTEM
Building remotely on mappy in workspace /ascldap/users/e3sm-jenkins/jenkins-ws/workspace/EKAT_PullRequest_Autotester_Mappy
The recommended git tool is: NONE
using credential cf1815d3-62c3-4157-a38d-0ad235093618
Wiping out workspace first.
Cloning the remote Git repository
Honoring refspec on initial clone
Cloning repository https://github.com/E3SM-Project/EKAT.git
 > git init /ascldap/users/e3sm-jenkins/jenkins-ws/workspace/EKAT_PullRequest_Autotester_Mappy/353/ekat-src # timeout=10
Fetching upstream changes from https://github.com/E3SM-Project/EKAT.git
 > git --version # timeout=10
 > git --version # 'git version 1.8.3.1'
using GIT_SSH to set credentials jgfouca github key
Setting http proxy: proxy.sandia.gov:80
 > git fetch --tags --progress https://github.com/E3SM-Project/EKAT.git +refs/heads/master:refs/remotes/origin/master +refs/pull/257/head:refs/heads/pr/257 # timeout=10
 > git config remote.origin.url https://github.com/E3SM-Project/EKAT.git # timeout=10
 > git config --add remote.origin.fetch +refs/heads/master:refs/remotes/origin/master # timeout=10
 > git config --add remote.origin.fetch +refs/pull/257/head:refs/heads/pr/257 # timeout=10
Avoid second fetch
 > git rev-parse refs/remotes/origin/pr/257^{commit} # timeout=10
 > git rev-parse pr/257^{commit} # timeout=10
JENKINS-19022: warning: possible memory leak due to Git plugin usage; see: https://plugins.jenkins.io/git/#remove-git-plugin-buildsbybranch-builddata-script
Checking out Revision c05f7b99a48143a106085c0e6353f9eb0b6d66fe (pr/257)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f c05f7b99a48143a106085c0e6353f9eb0b6d66fe # timeout=10
Commit message: "fix comments"
 > git rev-list --no-walk c05f7b99a48143a106085c0e6353f9eb0b6d66fe # timeout=10
 > git remote # timeout=10
 > git submodule init # timeout=10
 > git submodule sync # timeout=10
 > git config --get remote.origin.url # timeout=10
 > git submodule init # timeout=10
 > git config -f .gitmodules --get-regexp ^submodule\.(.+)\.url # timeout=10
 > git config --get submodule.extern/kokkos.url # timeout=10
 > git remote # timeout=10
 > git config --get remote.origin.url # timeout=10
 > git config -f .gitmodules --get submodule.extern/kokkos.path # timeout=10
 > git config --get submodule.extern/yaml-cpp.url # timeout=10
 > git remote # timeout=10
 > git config --get remote.origin.url # timeout=10
 > git config -f .gitmodules --get submodule.extern/yaml-cpp.path # timeout=10
 > git config --get submodule.extern/spdlog.url # timeout=10
 > git remote # timeout=10
 > git config --get remote.origin.url # timeout=10
 > git config -f .gitmodules --get submodule.extern/spdlog.path # timeout=10
 > git config --get submodule.extern/Catch2.url # timeout=10
 > git remote # timeout=10
 > git config --get remote.origin.url # timeout=10
 > git config -f .gitmodules --get submodule.extern/Catch2.path # timeout=10
using GIT_SSH to set credentials jgfouca github key
 > git submodule update --init --recursive extern/kokkos # timeout=5
hudson.plugins.git.GitException: Command "git submodule update --init --recursive extern/kokkos" returned status code 1:
stdout: Cloning into 'extern/kokkos'...

stderr: fatal: reference is not a tree: 24b3eb42ba72cc4ea4dae441916dd6db8dcb8613
Unable to checkout '24b3eb42ba72cc4ea4dae441916dd6db8dcb8613' in submodule path 'extern/kokkos'

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2675)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:2099)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$500(CliGitAPIImpl.java:85)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$7.lambda$execute$0(CliGitAPIImpl.java:1506)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:74)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutorService.execute(MoreExecutors.java:323)
	at java.util.concurrent.ExecutorCompletionService.submit(ExecutorCompletionService.java:181)
	at org.jenkinsci.plugins.gitclient.cgit.GitCommandsExecutor.submitRemainingCommand(GitCommandsExecutor.java:98)
	 [...]

2022-10-27 20:05 UTC, ambrad commented
@bartgol are you opposed to our grabbing 3.7, say, and then cherry-picking our special commits onto that and making a tag of the result?

2022-10-27 21:17 UTC, bartgol commented
> @bartgol are you opposed to our grabbing 3.7, say, and then cherry-picking our special commits onto that and making a tag of the result?

That's fine. I don't care how commits are organized in the tree, so long as we get the ones we added in our fork (there should be no more than 4 or 5).

2022-10-28 00:10 UTC, E3SM-Autotester commented
Status Flag 'Pre-Test Inspection' - Auto Inspected - Inspection Is Not Necessary for this Pull Request.

2022-10-28 00:12 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: EKAT_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 365</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>EKAT_SOURCE_BRANCH</td>
    <td>oksanaguba/crusher-changes-sept19</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_SHA</td>
    <td>85062686615d99547ddd494ef8b97f72b5c63a54</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_SHA</td>
    <td>1052776a2ee5cef2607515453124a0d7f007bf4d</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>257</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>EKAT</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: EKAT_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 462</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>EKAT_SOURCE_BRANCH</td>
    <td>oksanaguba/crusher-changes-sept19</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_SHA</td>
    <td>85062686615d99547ddd494ef8b97f72b5c63a54</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_SHA</td>
    <td>1052776a2ee5cef2607515453124a0d7f007bf4d</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>257</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>EKAT</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: EKAT_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 479</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>EKAT_SOURCE_BRANCH</td>
    <td>oksanaguba/crusher-changes-sept19</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_SHA</td>
    <td>85062686615d99547ddd494ef8b97f72b5c63a54</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_SHA</td>
    <td>1052776a2ee5cef2607515453124a0d7f007bf4d</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>257</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>EKAT</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: EKAT (E3SM-Project/EKAT)</dt>
  <ul>
    <li>Branch: oksanaguba/crusher-changes-sept19</li>
    <li>SHA: 85062686615d99547ddd494ef8b97f72b5c63a54</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

Pull Request Author: oksanaguba
</details>

2022-10-28 00:12 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Error: Jenkins Jobs - A user has commited a change to the PR before testing completed.  The original testing SHA = 85062686615d99547ddd494ef8b97f72b5c63a54 Does not match the current commit SHA = 598ed61bdf7039fae412d292f1ce9f6bd5fd5f30.  The Jenkins Jobs will be shutdown; Testing of this PR must occur again.

2022-10-28 00:12 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: 1 or more Jobs FAILED

Note: Testing will normally be attempted again in approx. 4 Hrs. If a change to the PR source branch occurs, the testing will be attempted again on next available autotester run.

<details>
<summary>
  <b>Pull Request Auto Testing has FAILED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: EKAT_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 365</li>
  <li>Status: ERROR</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>EKAT_SOURCE_BRANCH</td>
    <td>oksanaguba/crusher-changes-sept19</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_SHA</td>
    <td>85062686615d99547ddd494ef8b97f72b5c63a54</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_SHA</td>
    <td>1052776a2ee5cef2607515453124a0d7f007bf4d</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>257</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>EKAT</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: EKAT_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 462</li>
  <li>Status: ERROR</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>EKAT_SOURCE_BRANCH</td>
    <td>oksanaguba/crusher-changes-sept19</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_SHA</td>
    <td>85062686615d99547ddd494ef8b97f72b5c63a54</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_SHA</td>
    <td>1052776a2ee5cef2607515453124a0d7f007bf4d</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>257</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>EKAT</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: EKAT_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 479</li>
  <li>Status: ERROR</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>EKAT_SOURCE_BRANCH</td>
    <td>oksanaguba/crusher-changes-sept19</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_SHA</td>
    <td>85062686615d99547ddd494ef8b97f72b5c63a54</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_SHA</td>
    <td>1052776a2ee5cef2607515453124a0d7f007bf4d</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>257</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>EKAT</td>
  </tr>
</table>
</details>


<details>
<summary>
  <b>Console Output (last 100K lines) : EKAT_PullRequest_Autotester_Mappy # 365</b> (click to expand)
</summary>
<pre>
<code>
-- Installing: /ascldap/users/e3sm-jenkins/jenkins-ws/workspace/EKAT_PullRequest_Autotester_Mappy/365/ekat-install/ekat-sp/include/spdlog/fmt
-- Installing: /ascldap/users/e3sm-jenkins/jenkins-ws/workspace/EKAT_PullRequest_Autotester_Mappy/365/ekat-install/ekat-sp/include/spdlog/fmt/bin_to_hex.h
-- Installing: /ascldap/users/e3sm-jenkins/jenkins-ws/workspace/EKAT_PullRequest_Autotester_Mappy/365/ekat-install/ekat-sp/include/spdlog/fmt/chrono.h
-- Installing: /ascldap/users/e3sm-jenkins/jenkins-ws/workspace/EKAT_PullRequest_Autotester_Mappy/365/ekat-install/ekat-sp/include/spdlog/fmt/compile.h
-- Installing: /ascldap/users/e3sm-jenkins/jenkins-ws/workspace/EKAT_PullRequest_Autotester_Mappy/365/ekat-install/ekat-sp/include/spdlog/fmt/fmt.h
-- Installing: /ascldap/users/e3sm-jenkins/jenkins-ws/workspace/EKAT_PullRequest_Autotester_Mappy/365/ekat-install/ekat-sp/include/spdlog/fmt/ostr.h
-- Installing: /ascldap/users/e3sm-jenkins/jenkins-ws/workspace/EKAT_PullRequest_Autotester_Mappy/365/ekat-install/ekat-sp/include/spdlog/fmt/ranges.h
-- Installing: /ascldap/users/e3sm-jenkins/jenkins-ws/workspace/EKAT_PullRequest_Autotester_Mappy/365/ekat-install/ekat-sp/include/spdlog/fmt/xchar.h
-- Installing: /ascldap/users/e3sm-jenkins/jenkins-ws/workspace/EKAT_PullRequest_Autotester_Mappy/365/ekat-install/ekat-sp/include/spdlog/formatter.h
-- Installing: /ascldap/users/e3sm-jenkins/jenkins-ws/workspace/EKAT_PullRequest_Autotester_Mappy/365/ekat-install/ekat-sp/include/spdlog/fwd.h
-- Installing: /ascldap/users/e3sm-jenkins/jenkins-ws/workspace/EKAT_PullRequest_Autotester_Mappy/365/ekat-install/ekat-sp/include/spdlog/logger-inl.h
-- Installing: /ascldap/users/e3sm-jenkins/jenkins-ws/workspace/EKAT_PullRequest_Autotester_Mappy/365/ekat-install/ekat-sp/include/spdlog/logger.h
-- Installing: /ascldap/users/e3sm-jenkins/jenkins-ws/workspace/EKAT_PullRequest_Autotester_Mappy/365/ekat-install/ekat-sp/include/spdlog/pattern_formatter-inl.h
-- Installing: /ascldap/users/e3sm-jenkins/jenkins-ws/workspace/EKAT_PullRequest_Autotester_Mappy/365/ekat-install/ekat-sp/include/spdlog/pattern_formatter.h
-- Installing: /ascldap/users/e3sm-jenkins/jenkins-ws/workspace/EKAT_PullRequest_Autotester_Mappy/365/ekat-install/ekat-sp/include/spdlog/sinks
-- Installing: /ascldap/users/e3sm-jenkins/jenkins-ws/workspace/EKAT_PullRequest_Autotester_Mappy/365/ekat-install/ekat-sp/include/spdlog/sinks/android_sink.h
-- Installing: /ascldap/users/e3sm-jenkins/jenkins-ws/workspace/EKAT_PullRequest_Autotester_Mappy/365/ekat-install/ekat-sp/include/spdlog/sinks/ansicolor_sink-inl.h
-- Installing: /ascldap/users/e3sm-jenkins/jenkins-ws/workspace/EKAT_PullRequest_Autotester_Mappy/365/ekat-install/ekat-sp/include/spdlog/sinks/ansicolor_sink.h
-- Installing: /ascldap/users/e3sm-jenkins/jenkins-ws/workspace/EKAT_PullRequest_Autotester_Mappy/365/ekat-install/ekat-sp/include/spdlog/sinks/base_sink-inl.h
-- Installing: /ascldap/users/e3sm-jenkins/jenkins-ws/workspace/EKAT_PullRequest_Autotester_Mappy/365/ekat-install/ekat-sp/include/spdlog/sinks/base_sink.h
-- Installing: /ascldap/users/e3sm-jenkins/jenkins-ws/workspace/EKAT_PullRequest_Autotester_Mappy/365/ekat-install/ekat-sp/include/spdlog/sinks/basic_file_sink-inl.h
-- Installing: /ascldap/users/e3sm-jenkins/jenkins-ws/workspace/EKAT_PullRequest_Autotester_Mappy/365/ekat-install/ekat-sp/include/spdlog/sinks/basic_file_sink.h
-- Installing: /ascldap/users/e3sm-jenkins/jenkins-ws/workspace/EKAT_PullRequest_Autotester_Mappy/365/ekat-install/ekat-sp/include/spdlog/sinks/daily_file_sink.h
-- Installing: /ascldap/users/e3sm-jenkins/jenkins-ws/workspace/EKAT_PullRequest_Autotester_Mappy/365/ekat-install/ekat-sp/include/spdlog/sinks/dist_sink.h
-- Installing: /ascldap/users/e3sm-jenkins/jenkins-ws/workspace/EKAT_PullRequest_Autotester_Mappy/365/ekat-install/ekat-sp/include/spdlog/sinks/dup_filter_sink.h
-- Installing: /ascldap/users/e3sm-jenkins/jenkins-ws/workspace/EKAT_PullRequest_Autotester_Mappy/365/ekat-install/ekat-sp/include/spdlog/sinks/hourly_file_sink.h
-- Installing: /ascldap/users/e3sm-jenkins/jenkins-ws/workspace/EKAT_PullRequest_Autotester_Mappy/365/ekat-install/ekat-sp/include/spdlog/sinks/mongo_sink.h
-- Installing: /ascldap/users/e3sm-jenkins/jenkins-ws/workspace/EKAT_PullRequest_Autotester_Mappy/365/ekat-install/ekat-sp/include/spdlog/sinks/msvc_sink.h
-- Installing: /ascldap/users/e3sm-jenkins/jenkins-ws/workspace/EKAT_PullRequest_Autotester_Mappy/365/ekat-install/ekat-sp/include/spdlog/sinks/null_sink.h
-- Installing: /ascldap/users/e3sm-jenkins/j [...]

2022-10-28 04:46 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: EKAT_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 366</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>EKAT_SOURCE_BRANCH</td>
    <td>oksanaguba/crusher-changes-sept19</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_SHA</td>
    <td>85062686615d99547ddd494ef8b97f72b5c63a54</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_SHA</td>
    <td>3eb2bfadd86750465072dfbc2ae837ecd2410127</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>257</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>EKAT</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: EKAT_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 463</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>EKAT_SOURCE_BRANCH</td>
    <td>oksanaguba/crusher-changes-sept19</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_SHA</td>
    <td>85062686615d99547ddd494ef8b97f72b5c63a54</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_SHA</td>
    <td>3eb2bfadd86750465072dfbc2ae837ecd2410127</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>257</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>EKAT</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: EKAT_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 480</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>EKAT_SOURCE_BRANCH</td>
    <td>oksanaguba/crusher-changes-sept19</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_SHA</td>
    <td>85062686615d99547ddd494ef8b97f72b5c63a54</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_SHA</td>
    <td>3eb2bfadd86750465072dfbc2ae837ecd2410127</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>257</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>EKAT</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: EKAT (E3SM-Project/EKAT)</dt>
  <ul>
    <li>Branch: oksanaguba/crusher-changes-sept19</li>
    <li>SHA: 85062686615d99547ddd494ef8b97f72b5c63a54</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

Pull Request Author: oksanaguba
</details>

2022-10-28 04:59 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: all Jobs PASSED

<details>
<summary>
  <b>Pull Request Auto Testing has PASSED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: EKAT_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 366</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>EKAT_SOURCE_BRANCH</td>
    <td>oksanaguba/crusher-changes-sept19</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_SHA</td>
    <td>85062686615d99547ddd494ef8b97f72b5c63a54</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_SHA</td>
    <td>3eb2bfadd86750465072dfbc2ae837ecd2410127</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>257</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>EKAT</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: EKAT_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 463</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>EKAT_SOURCE_BRANCH</td>
    <td>oksanaguba/crusher-changes-sept19</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_SHA</td>
    <td>85062686615d99547ddd494ef8b97f72b5c63a54</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_SHA</td>
    <td>3eb2bfadd86750465072dfbc2ae837ecd2410127</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>257</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>EKAT</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: EKAT_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 480</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>EKAT_SOURCE_BRANCH</td>
    <td>oksanaguba/crusher-changes-sept19</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_SHA</td>
    <td>85062686615d99547ddd494ef8b97f72b5c63a54</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_SHA</td>
    <td>3eb2bfadd86750465072dfbc2ae837ecd2410127</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>257</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>EKAT</td>
  </tr>
</table>
</details>

2022-10-28 04:59 UTC, E3SM-Autotester commented
Status Flag 'Pre-Merge Inspection' - - This Pull Request Requires Inspection... The code must be inspected by a member of the Team before Testing/Merging
           THE LAST COMMIT TO THIS PULL REQUEST HAS NOT BEEN REVIEWED YET!

2022-10-28 04:59 UTC, E3SM-Autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2022-10-28 05:36 UTC, bartgol commented on cmake/machine-files/kokkos/hip.cmake
> +set(Kokkos_ENABLE_AGGRESSIVE_VECTORIZATION FALSE CACHE BOOL "")
Grepping the kokkos repo suggests this only matters for OpenMP and Threads backends.

2022-10-28 05:36 UTC, bartgol approved these changes

2022-10-28 05:39 UTC, E3SM-Autotester commented
Status Flag 'Pre-Merge Inspection' - SUCCESS: The last commit to this Pull Request has been INSPECTED AND APPROVED by [ bartgol ]!

2022-10-28 05:39 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - AutoMerge IS ENABLED, but the Label AT: AUTOMERGE is not set.  Either set Label AT: AUTOMERGE or manually merge the PR...

2022-10-29 06:09 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - AutoMerge IS ENABLED, but the Label AT: AUTOMERGE is not set.  Either set Label AT: AUTOMERGE or manually merge the PR...

2022-10-29 06:14 UTC, ambrad commented
@oksanaguba @bartgol are you ready to merge this? If so, it would be good to have this in before https://github.com/E3SM-Project/scream/pull/1797. Then that PR should have the ekat submodule updated to point to EKAT's updated master.

2022-10-29 06:53 UTC, oksanaguba commented
I am ready, not sure what's required wrt testing for ekat.

2022-10-30 06:39 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - AutoMerge IS ENABLED, but the Label AT: AUTOMERGE is not set.  Either set Label AT: AUTOMERGE or manually merge the PR...

2022-10-30 17:38 UTC, oksanaguba commented
Since AT tested it, can this be merged? Should i press the green button?

2022-10-31 07:09 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - AutoMerge IS ENABLED, but the Label AT: AUTOMERGE is not set.  Either set Label AT: AUTOMERGE or manually merge the PR...

2022-10-31 14:57 UTC, bartgol commented
Ok, let's merge.

2022-10-31 14:57 UTC, merged