Add cmake utility to create tests for asserts
E3SM-Project/EKAT pull request #334
Opened 2024-04-15 23:54 UTC by bartgol

## Motivation

The Catch2 framework does not offer a way to test that an assertion fails. It has `REQUIRE_THROWS`, but that only works with _exception_, not _assertions_. I found online a library that can test assertions via `setjmp` and the likes, but I'm not sure this would work correctly for device code. So I decided to roll our own testing mechanism. The idea is simple: wrap every "bad" call in `EKAT_TEST_ASSERT(...)`. This macro is never defined, but the cmake+python utility will use this special string to generate a test. In particular:
- we generate a separate unit test for each `EKAT_TEST_ASSERT (...)` line
- while testing the n-th occurrence of the `EKAT_TEST_ASSERT` string, remove all lines containing that string, except for the current one, where it will simply remove `EKAT_TEST_ASSERT`.
- since `EKAT_TEST_ASSERT` is simply removed from the line to test, it doesn't really matter where it appears in the line; it can even be a comment at the end:
```
   bad_call (); // EKAT_TEST_ASSERT
```
- the bad function call must fit in a single line, together with EKAT_TEST_ASSERT. Implementing a smarter multi-line parser (which would require a "macro-like" implementation, rather than the "comment" version in the point above) is harder, and I didn't want to spend more time on this.
- the utility can only accept a _single_ source cpp file as input
- for each line to test, we generate a separate src file in the build folder, and then we invoke the usual `EkatCreateUnitTest` with that file.
- the utility has no knowledge about NDEBUG. It's up to the user to use `EkatCreateAssertTest` only in debug builds.

## Testing

I added some dummy tests that verify this mechanism works.

2024-04-16 00:10 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: EKAT_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 508</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>EKAT_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_SHA</td>
    <td>a697a689f3fbdf01312939587a200071a187f731</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_SHA</td>
    <td>0811e6cad49b0f10d6c343bb6fed97e6e98fb794</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>cmake;AT: AUTOMERGE</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>334</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>EKAT</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: EKAT_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 594</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>EKAT_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_SHA</td>
    <td>a697a689f3fbdf01312939587a200071a187f731</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_SHA</td>
    <td>0811e6cad49b0f10d6c343bb6fed97e6e98fb794</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>cmake;AT: AUTOMERGE</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>334</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>EKAT</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: EKAT (E3SM-Project/EKAT)</dt>
  <ul>
    <li>Branch: bartgol/test-assert</li>
    <li>SHA: a697a689f3fbdf01312939587a200071a187f731</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

Pull Request Author: bartgol
</details>

2024-04-16 00:23 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: all Jobs PASSED

<details>
<summary>
  <b>Pull Request Auto Testing has PASSED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: EKAT_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 508</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>EKAT_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_SHA</td>
    <td>a697a689f3fbdf01312939587a200071a187f731</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_SHA</td>
    <td>0811e6cad49b0f10d6c343bb6fed97e6e98fb794</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>cmake;AT: AUTOMERGE</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>334</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>EKAT</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: EKAT_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 594</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>EKAT_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_SHA</td>
    <td>a697a689f3fbdf01312939587a200071a187f731</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_SHA</td>
    <td>0811e6cad49b0f10d6c343bb6fed97e6e98fb794</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>cmake;AT: AUTOMERGE</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>334</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>EKAT</td>
  </tr>
</table>
</details>

2024-04-16 00:23 UTC, E3SM-Autotester commented
Status Flag 'Pre-Merge Inspection' - - This Pull Request Requires Inspection... The code must be inspected by a member of the Team before Testing/Merging
           NO REVIEWS HAVE BEEN PERFORMED ON THIS PULL REQUEST!

2024-04-16 00:23 UTC, E3SM-Autotester commented
All Jobs Finished; status = PASSED, target_sha=0811e6cad49b0f10d6c343bb6fed97e6e98fb794, However Inspection must be performed before merge can occur...

2024-04-16 21:21 UTC, tcclevenger reviewed
This looks good to me, but I'll give @jgfouca a chance to look since he's more familiar with the cmake.

2024-04-16 22:02 UTC, E3SM-Autotester commented
Status Flag 'Pre-Merge Inspection' - - This Pull Request Requires Inspection... The code must be inspected by a member of the Team before Testing/Merging
           THE LAST COMMIT TO THIS PULL REQUEST HAS BEEN REVIEWED, BUT NOT ACCEPTED OR REQUIRES CHANGES!

2024-04-16 22:02 UTC, E3SM-Autotester commented
All Jobs Finished; status = PASSED, target_sha=0811e6cad49b0f10d6c343bb6fed97e6e98fb794, However Inspection must be performed before merge can occur...

2024-04-17 16:43 UTC, jgfouca requested changes
One minor thought, otherwise looks good.

2024-04-17 16:43 UTC, jgfouca commented on cmake/EkatCreateUnitTestWithAsserts.cmake
> +# are compiled away or not (i.e., whether the macro NDEBUG is present
CMake should know if the build is debug or not. We can use `EKAT_IS_DEBUG_BUILD` or `CMAKE_BUILD_TYPE`. We could maybe just have this function do nothing if it's not a debug build, that way the users of this function won't have to remember to guard the call.

2024-04-17 19:46 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: EKAT_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 509</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>EKAT_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_SHA</td>
    <td>cf12df6b8aa5a2a484a643a6f8d4f4f1eeb0643a</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_SHA</td>
    <td>0811e6cad49b0f10d6c343bb6fed97e6e98fb794</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>cmake</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>334</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>EKAT</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: EKAT_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 595</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>EKAT_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_SHA</td>
    <td>cf12df6b8aa5a2a484a643a6f8d4f4f1eeb0643a</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_SHA</td>
    <td>0811e6cad49b0f10d6c343bb6fed97e6e98fb794</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>cmake</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>334</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>EKAT</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: EKAT (E3SM-Project/EKAT)</dt>
  <ul>
    <li>Branch: bartgol/test-assert</li>
    <li>SHA: cf12df6b8aa5a2a484a643a6f8d4f4f1eeb0643a</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

Pull Request Author: bartgol
</details>

2024-04-17 19:58 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: all Jobs PASSED

<details>
<summary>
  <b>Pull Request Auto Testing has PASSED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: EKAT_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 509</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>EKAT_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_SHA</td>
    <td>cf12df6b8aa5a2a484a643a6f8d4f4f1eeb0643a</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_SHA</td>
    <td>0811e6cad49b0f10d6c343bb6fed97e6e98fb794</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>cmake</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>334</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>EKAT</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: EKAT_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 595</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>EKAT_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_SHA</td>
    <td>cf12df6b8aa5a2a484a643a6f8d4f4f1eeb0643a</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_SHA</td>
    <td>0811e6cad49b0f10d6c343bb6fed97e6e98fb794</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>cmake</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>334</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>EKAT</td>
  </tr>
</table>
</details>

2024-04-17 19:58 UTC, E3SM-Autotester commented
Status Flag 'Pre-Merge Inspection' - - This Pull Request Requires Inspection... The code must be inspected by a member of the Team before Testing/Merging
           THE LAST COMMIT TO THIS PULL REQUEST HAS NOT BEEN REVIEWED YET!

2024-04-17 19:58 UTC, E3SM-Autotester commented
All Jobs Finished; status = PASSED, target_sha=0811e6cad49b0f10d6c343bb6fed97e6e98fb794, However Inspection must be performed before merge can occur...

2024-04-17 20:48 UTC, jgfouca approved these changes

2024-04-17 20:49 UTC, tcclevenger approved these changes

2024-04-17 21:30 UTC, merged