Fix RepackType when packing const scalar data
E3SM-Project/EKAT pull request #346
Opened 2024-07-25 16:05 UTC by bartgol

## Motivation

Calling `repack` passing a view of const scalar data type (not a `const Pack<T,N>`) in LinInterp::setup was causing an error, since the output of `repack` was a `View<const Pack<const T,N>,...>`, which is not compatible with what `setup_impl` expected, which is `View<const Pack<T,N>>`. The fix is very quick, though, and I manually verified that I can now call LinInterp::setup passing views of const doubles.

Note: everything was already working fine passing views of const packs, since the meta utility `RepackType` was already handling const correctly for pack types.

## E3SM Stakeholder Feedback

2024-07-25 16:11 UTC, tcclevenger approved these changes

2024-07-25 16:13 UTC, tcclevenger requested changes
Before this merges, I'll revoke my review just to ask if it would be simple to add this case to the Linear interp tests?

Edit: maybe you already addressed this in your last paragraph..

2024-07-25 16:23 UTC, tcclevenger approved these changes
I'll reaprove and take off automerge. You can add it back if a test is unnecessary.

2024-07-25 16:25 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: all Jobs PASSED

<details>
<summary>
  <b>Pull Request Auto Testing has PASSED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: EKAT_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 522</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>EKAT_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_SHA</td>
    <td>27693469ad40548345e51188a34f2cf029fbb6e6</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_SHA</td>
    <td>594801fc1f855b862a13dd503cb64207c33cd91c</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>bugfix;AT: AUTOMERGE;Packs;code usability</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>346</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>EKAT</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: EKAT_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 608</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>EKAT_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_SHA</td>
    <td>27693469ad40548345e51188a34f2cf029fbb6e6</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_SHA</td>
    <td>594801fc1f855b862a13dd503cb64207c33cd91c</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>bugfix;AT: AUTOMERGE;Packs;code usability</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>346</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>EKAT</td>
  </tr>
</table>
</details>

2024-07-25 16:25 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - AutoMerge IS ENABLED, but the Label AT: AUTOMERGE is not set.  Either set Label AT: AUTOMERGE or manually merge the PR...

2024-07-25 16:31 UTC, bartgol commented
> Before this merges, I'll revoke my review just to ask if it would be simple to add this case to the Linear interp tests?
> 
> Edit: maybe you already addressed this in your last paragraph..

The repack function cannot work for, say, `View<const double*>` unless we add this fix. We virtually never use `Pack<const T,N>`, but prefer to use `const Pack<T,N>` everywhere, so it makes sense to me to ensure that RepackType<...>::type _never_ returns a `Pack<const T, N>`.

2024-07-26 16:39 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - AutoMerge IS ENABLED, but the Label AT: AUTOMERGE is not set.  Either set Label AT: AUTOMERGE or manually merge the PR...

2024-07-26 16:53 UTC, bartgol commented
@tcclevenger sorry, I think I misread your comment. I thought you wanted to move the fix into the LinInterp class, which is impossible. Now I understand you meant to add a test for repacking view of const data. I can add that in the repack unit tests.

2024-07-26 17:14 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: EKAT_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 523</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>EKAT_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_SHA</td>
    <td>53c168c20edadf732d6293bf9dbf136b48e5ea4e</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_SHA</td>
    <td>594801fc1f855b862a13dd503cb64207c33cd91c</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>bugfix;AT: AUTOMERGE;Packs;code usability</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>346</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>EKAT</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: EKAT_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 609</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>EKAT_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_SHA</td>
    <td>53c168c20edadf732d6293bf9dbf136b48e5ea4e</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_SHA</td>
    <td>594801fc1f855b862a13dd503cb64207c33cd91c</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>bugfix;AT: AUTOMERGE;Packs;code usability</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>346</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>EKAT</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: EKAT (E3SM-Project/EKAT)</dt>
  <ul>
    <li>Branch: bartgol/fix-repack-for-view-of-const-data</li>
    <li>SHA: 53c168c20edadf732d6293bf9dbf136b48e5ea4e</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

Pull Request Author: bartgol
</details>

2024-07-26 17:28 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: all Jobs PASSED

<details>
<summary>
  <b>Pull Request Auto Testing has PASSED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: EKAT_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 523</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>EKAT_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_SHA</td>
    <td>53c168c20edadf732d6293bf9dbf136b48e5ea4e</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_SHA</td>
    <td>594801fc1f855b862a13dd503cb64207c33cd91c</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>bugfix;AT: AUTOMERGE;Packs;code usability</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>346</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>EKAT</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: EKAT_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 609</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>EKAT_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_SHA</td>
    <td>53c168c20edadf732d6293bf9dbf136b48e5ea4e</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_SHA</td>
    <td>594801fc1f855b862a13dd503cb64207c33cd91c</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>bugfix;AT: AUTOMERGE;Packs;code usability</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>346</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>EKAT</td>
  </tr>
</table>
</details>

2024-07-26 17:28 UTC, E3SM-Autotester commented
Status Flag 'Pre-Merge Inspection' - - This Pull Request Requires Inspection... The code must be inspected by a member of the Team before Testing/Merging
           THE LAST COMMIT TO THIS PULL REQUEST HAS NOT BEEN REVIEWED YET!

2024-07-26 17:29 UTC, E3SM-Autotester commented
All Jobs Finished; status = PASSED, target_sha=594801fc1f855b862a13dd503cb64207c33cd91c, However Inspection must be performed before merge can occur...

2024-07-26 18:08 UTC, tcclevenger approved these changes

2024-07-26 18:09 UTC, merged