make expm1 avail to packs
E3SM-Project/EKAT pull request #47
Opened 2020-09-17 20:10 UTC by PeterCaldwell

## Motivation
Make expm1 intrinsic available to pack data.

## Related Issues
Needed by SCREAM PR #554

## Testing
Skipping addition of new test because change is super basic. Is this ok?

2020-09-17 20:16 UTC, bartgol requested changes
Could you add a one line change in `pack_tests.cpp` to make sure this is tested alongside all other std::blah functions?

2020-09-17 20:25 UTC, PeterCaldwell commented
> Could you add a one line change in `pack_tests.cpp` to make sure this is tested alongside all other std::blah functions?

Sorry - it was lazy of me to not figure this out on my own. Test added.

2020-09-17 20:25 UTC, bartgol submitted a review, later dismissed

2020-09-17 22:42 UTC, E3SM-Autotester commented
Status Flag 'Pre-Test Inspection' - Auto Inspected - Inspection Is Not Necessary for this Pull Request.

2020-09-17 22:43 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: EKAT_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 47</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>EKAT_SOURCE_BRANCH</td>
    <td>PeterCaldwell/add_expm1</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_SHA</td>
    <td>3aae8e4173c3e1e5713f89c0587f98eb249d76e4</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_SHA</td>
    <td>746968a8a524643787c82b344cfc12f8c18d1a12</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;Packs</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>47</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>EKAT</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: EKAT_PullRequest_Autotester_Bowman</h3>
<ul>
  <li>Build Num: 43</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>EKAT_SOURCE_BRANCH</td>
    <td>PeterCaldwell/add_expm1</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_SHA</td>
    <td>3aae8e4173c3e1e5713f89c0587f98eb249d76e4</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_SHA</td>
    <td>746968a8a524643787c82b344cfc12f8c18d1a12</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;Packs</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>47</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>EKAT</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: EKAT_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 47</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>EKAT_SOURCE_BRANCH</td>
    <td>PeterCaldwell/add_expm1</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_SHA</td>
    <td>3aae8e4173c3e1e5713f89c0587f98eb249d76e4</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_SHA</td>
    <td>746968a8a524643787c82b344cfc12f8c18d1a12</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;Packs</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>47</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>EKAT</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: EKAT (E3SM-Project/EKAT)</dt>
  <ul>
    <li>Branch: PeterCaldwell/add_expm1</li>
    <li>SHA: 3aae8e4173c3e1e5713f89c0587f98eb249d76e4</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

Pull Request Author: PeterCaldwell
</details>

2020-09-17 22:44 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: 1 or more Jobs FAILED

Note: Testing will normally be attempted again in approx. 4 Hrs. If a change to the PR source branch occurs, the testing will be attempted again on next available autotester run.

<details>
<summary>
  <b>Pull Request Auto Testing has FAILED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: EKAT_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 47</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>EKAT_SOURCE_BRANCH</td>
    <td>PeterCaldwell/add_expm1</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_SHA</td>
    <td>3aae8e4173c3e1e5713f89c0587f98eb249d76e4</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_SHA</td>
    <td>746968a8a524643787c82b344cfc12f8c18d1a12</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;Packs</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>47</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>EKAT</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: EKAT_PullRequest_Autotester_Bowman</h3>
<ul>
  <li>Build Num: 43</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>EKAT_SOURCE_BRANCH</td>
    <td>PeterCaldwell/add_expm1</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_SHA</td>
    <td>3aae8e4173c3e1e5713f89c0587f98eb249d76e4</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_SHA</td>
    <td>746968a8a524643787c82b344cfc12f8c18d1a12</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;Packs</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>47</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>EKAT</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: EKAT_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 47</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>EKAT_SOURCE_BRANCH</td>
    <td>PeterCaldwell/add_expm1</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_SHA</td>
    <td>3aae8e4173c3e1e5713f89c0587f98eb249d76e4</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_SHA</td>
    <td>746968a8a524643787c82b344cfc12f8c18d1a12</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;Packs</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>47</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>EKAT</td>
  </tr>
</table>
</details>


<details>
<summary>
  <b>Console Output (last 100 lines) : EKAT_PullRequest_Autotester_Blake # 47</b> (click to expand)
</summary>
<pre>
<code>
 src/ekat/util/ekat_math_utils.hpp                  |  15 +-
 src/ekat/util/ekat_md_array.hpp                    |  14 +-
 src/ekat/util/ekat_rational_constant.hpp           |   4 +-
 src/ekat/util/ekat_scaling_factor.hpp              |   5 -
 src/ekat/util/ekat_string_utils.cpp                |  70 +++++-
 src/ekat/util/ekat_string_utils.hpp                |  24 +-
 src/ekat/util/ekat_test_session.cpp                |   2 +-
 src/ekat/util/ekat_test_utils.cpp                  |   2 -
 src/ekat/util/ekat_test_utils.hpp                  |   4 +-
 src/ekat/util/ekat_tridiag.hpp                     |   8 +-
 src/ekat/util/ekat_units.hpp                       |  13 +-
 src/ekat/util/ekat_upper_bound.hpp                 |   2 -
 tests/CMakeLists.txt                               |   6 +-
 tests/algorithm/CMakeLists.txt                     |   8 +-
 tests/algorithm/lin_interp_test.cpp                |  30 +--
 tests/algorithm/tridiag_bfb.cpp                    |  13 +-
 tests/algorithm/tridiag_tests.cpp                  |   4 +-
 tests/algorithm/tridiag_tests.hpp                  |   2 -
 tests/algorithm/tridiag_tests_correctness.cpp      |  68 +++---
 tests/algorithm/tridiag_tests_performance.cpp      |  36 ++-
 tests/io/CMakeLists.txt                            |   3 -
 tests/kokkos/CMakeLists.txt                        |   4 -
 tests/kokkos/kokkos_utils_tests.cpp                | 170 ++++++++++++-
 tests/kokkos/workspace_tests.cpp                   |  19 +-
 tests/pack/CMakeLists.txt                          |   5 +-
 tests/pack/pack_kokkos_tests.cpp                   |  85 ++++---
 tests/pack/pack_tests.cpp                          |  50 +++-
 tests/pack/pack_utils_tests.cpp                    |  61 +++++
 tests/utils/CMakeLists.txt                         |   9 +-
 tests/utils/debug_tools_tests.cpp                  |  19 +-
 tests/utils/upper_bound_test.cpp                   |   2 +-
 tests/utils/util_tests.cpp                         |  89 +++++--
 84 files changed, 1631 insertions(+), 640 deletions(-)
 create mode 100644 .gitmodules
 create mode 100644 cmake/EkatConfig.cmake.in
 delete mode 100644 cmake/Kokkos.cmake
 delete mode 100644 cmake/YamlCpp.cmake
 rename cmake/{ => mpi}/EkatMpiUtils.cmake (100%)
 rename cmake/{ => mpi}/EkatSetNvccWrapper.cmake (82%)
 rename cmake/{ => mpi}/TryCompileMPICH.cpp (100%)
 rename cmake/{ => mpi}/TryCompileOpenMPI.cpp (100%)
 rename cmake/{Ekat.cmake => pkg_build/EkatBuildEkat.cmake} (84%)
 create mode 100644 cmake/pkg_build/EkatBuildKokkos.cmake
 create mode 100644 cmake/pkg_build/EkatBuildYamlCpp.cmake
 create mode 160000 extern/kokkos
 create mode 160000 extern/yaml-cpp
 rename ekat_config.h.in => src/ekat/ekat_config.h.in (64%)
 create mode 100644 src/ekat/ekat_pack_utils.hpp
 create mode 100644 src/ekat/util/ekat_feutils.hpp
 create mode 100644 tests/pack/pack_utils_tests.cpp
+ cd /home/e3sm-jenkins/blake/workspace/EKAT_PullRequest_Autotester_Blake
+ '[' 0 -ne 0 ']'
+ FAILED_SP=
+ FAILED_DP=
+ RET_SP=0
+ RET_DP=0
+ mkdir -p ekat-build/ekat-sp
+ cd ekat-build/ekat-sp
+ rm -rf '*'
+ cmake -C /home/e3sm-jenkins/blake/workspace/EKAT_PullRequest_Autotester_Blake/ekat-src/cmake/machine-files/blake.cmake -DCMAKE_INSTALL_PREFIX=/home/e3sm-jenkins/blake/workspace/EKAT_PullRequest_Autotester_Blake/ekat-install/ekat-sp -DCMAKE_BUILD_TYPE=DEBUG -DCMAKE_CXX_COMPILER=mpicxx -DCMAKE_Fortran_COMPILER=mpifort -DEKAT_DISABLE_TPL_WARNINGS=ON -DEKAT_ENABLE_TESTS=ON -DEKAT_TEST_DOUBLE_PRECISION=OFF -DEKAT_TEST_SINGLE_PRECISION=ON /home/e3sm-jenkins/blake/workspace/EKAT_PullRequest_Autotester_Blake/ekat-src
loading initial cache file /home/e3sm-jenkins/blake/workspace/EKAT_PullRequest_Autotester_Blake/ekat-src/cmake/machine-files/blake.cmake
-- The CXX compiler identification is Intel 19.0.0.20181018
-- The Fortran compiler identification is Intel 19.0.0.20181018
-- Check for working CXX compiler: /home/projects/x86-64-skylake/openmpi/2.1.5/intel/19.1.144/bin/mpicxx
-- Check for working CXX compiler: /home/projects/x86-64-skylake/openmpi/2.1.5/intel/19.1.144/bin/mpicxx -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working Fortran compiler: /home/projects/x86-64-skylake/openmpi/2.1.5/intel/19.1.144/bin/mpifort
-- Check for working Fortran compiler: /home/projects/x86-64-skylake/openmpi/2.1.5/intel/19.1.144/bin/mpifort  -- works
-- Detecting Fortran compiler ABI info
-- Detecting Fortran c [...]

2020-09-18 03:18 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: EKAT_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 48</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>EKAT_SOURCE_BRANCH</td>
    <td>PeterCaldwell/add_expm1</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_SHA</td>
    <td>3aae8e4173c3e1e5713f89c0587f98eb249d76e4</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_SHA</td>
    <td>746968a8a524643787c82b344cfc12f8c18d1a12</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;Packs</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>47</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>EKAT</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: EKAT_PullRequest_Autotester_Bowman</h3>
<ul>
  <li>Build Num: 44</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>EKAT_SOURCE_BRANCH</td>
    <td>PeterCaldwell/add_expm1</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_SHA</td>
    <td>3aae8e4173c3e1e5713f89c0587f98eb249d76e4</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_SHA</td>
    <td>746968a8a524643787c82b344cfc12f8c18d1a12</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;Packs</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>47</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>EKAT</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: EKAT_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 48</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>EKAT_SOURCE_BRANCH</td>
    <td>PeterCaldwell/add_expm1</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_SHA</td>
    <td>3aae8e4173c3e1e5713f89c0587f98eb249d76e4</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_SHA</td>
    <td>746968a8a524643787c82b344cfc12f8c18d1a12</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;Packs</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>47</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>EKAT</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: EKAT (E3SM-Project/EKAT)</dt>
  <ul>
    <li>Branch: PeterCaldwell/add_expm1</li>
    <li>SHA: 3aae8e4173c3e1e5713f89c0587f98eb249d76e4</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

Pull Request Author: PeterCaldwell
</details>

2020-09-18 03:19 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: 1 or more Jobs FAILED

Note: Testing will normally be attempted again in approx. 4 Hrs. If a change to the PR source branch occurs, the testing will be attempted again on next available autotester run.

<details>
<summary>
  <b>Pull Request Auto Testing has FAILED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: EKAT_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 48</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>EKAT_SOURCE_BRANCH</td>
    <td>PeterCaldwell/add_expm1</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_SHA</td>
    <td>3aae8e4173c3e1e5713f89c0587f98eb249d76e4</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_SHA</td>
    <td>746968a8a524643787c82b344cfc12f8c18d1a12</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;Packs</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>47</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>EKAT</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: EKAT_PullRequest_Autotester_Bowman</h3>
<ul>
  <li>Build Num: 44</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>EKAT_SOURCE_BRANCH</td>
    <td>PeterCaldwell/add_expm1</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_SHA</td>
    <td>3aae8e4173c3e1e5713f89c0587f98eb249d76e4</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_SHA</td>
    <td>746968a8a524643787c82b344cfc12f8c18d1a12</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;Packs</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>47</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>EKAT</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: EKAT_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 48</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>EKAT_SOURCE_BRANCH</td>
    <td>PeterCaldwell/add_expm1</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_SHA</td>
    <td>3aae8e4173c3e1e5713f89c0587f98eb249d76e4</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_SHA</td>
    <td>746968a8a524643787c82b344cfc12f8c18d1a12</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;Packs</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>47</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>EKAT</td>
  </tr>
</table>
</details>


<details>
<summary>
  <b>Console Output (last 100 lines) : EKAT_PullRequest_Autotester_Blake # 48</b> (click to expand)
</summary>
<pre>
<code>
 src/ekat/util/ekat_math_utils.hpp                  |  15 +-
 src/ekat/util/ekat_md_array.hpp                    |  14 +-
 src/ekat/util/ekat_rational_constant.hpp           |   4 +-
 src/ekat/util/ekat_scaling_factor.hpp              |   5 -
 src/ekat/util/ekat_string_utils.cpp                |  70 +++++-
 src/ekat/util/ekat_string_utils.hpp                |  24 +-
 src/ekat/util/ekat_test_session.cpp                |   2 +-
 src/ekat/util/ekat_test_utils.cpp                  |   2 -
 src/ekat/util/ekat_test_utils.hpp                  |   4 +-
 src/ekat/util/ekat_tridiag.hpp                     |   8 +-
 src/ekat/util/ekat_units.hpp                       |  13 +-
 src/ekat/util/ekat_upper_bound.hpp                 |   2 -
 tests/CMakeLists.txt                               |   6 +-
 tests/algorithm/CMakeLists.txt                     |   8 +-
 tests/algorithm/lin_interp_test.cpp                |  30 +--
 tests/algorithm/tridiag_bfb.cpp                    |  13 +-
 tests/algorithm/tridiag_tests.cpp                  |   4 +-
 tests/algorithm/tridiag_tests.hpp                  |   2 -
 tests/algorithm/tridiag_tests_correctness.cpp      |  68 +++---
 tests/algorithm/tridiag_tests_performance.cpp      |  36 ++-
 tests/io/CMakeLists.txt                            |   3 -
 tests/kokkos/CMakeLists.txt                        |   4 -
 tests/kokkos/kokkos_utils_tests.cpp                | 170 ++++++++++++-
 tests/kokkos/workspace_tests.cpp                   |  19 +-
 tests/pack/CMakeLists.txt                          |   5 +-
 tests/pack/pack_kokkos_tests.cpp                   |  85 ++++---
 tests/pack/pack_tests.cpp                          |  50 +++-
 tests/pack/pack_utils_tests.cpp                    |  61 +++++
 tests/utils/CMakeLists.txt                         |   9 +-
 tests/utils/debug_tools_tests.cpp                  |  19 +-
 tests/utils/upper_bound_test.cpp                   |   2 +-
 tests/utils/util_tests.cpp                         |  89 +++++--
 84 files changed, 1631 insertions(+), 640 deletions(-)
 create mode 100644 .gitmodules
 create mode 100644 cmake/EkatConfig.cmake.in
 delete mode 100644 cmake/Kokkos.cmake
 delete mode 100644 cmake/YamlCpp.cmake
 rename cmake/{ => mpi}/EkatMpiUtils.cmake (100%)
 rename cmake/{ => mpi}/EkatSetNvccWrapper.cmake (82%)
 rename cmake/{ => mpi}/TryCompileMPICH.cpp (100%)
 rename cmake/{ => mpi}/TryCompileOpenMPI.cpp (100%)
 rename cmake/{Ekat.cmake => pkg_build/EkatBuildEkat.cmake} (84%)
 create mode 100644 cmake/pkg_build/EkatBuildKokkos.cmake
 create mode 100644 cmake/pkg_build/EkatBuildYamlCpp.cmake
 create mode 160000 extern/kokkos
 create mode 160000 extern/yaml-cpp
 rename ekat_config.h.in => src/ekat/ekat_config.h.in (64%)
 create mode 100644 src/ekat/ekat_pack_utils.hpp
 create mode 100644 src/ekat/util/ekat_feutils.hpp
 create mode 100644 tests/pack/pack_utils_tests.cpp
+ cd /home/e3sm-jenkins/blake/workspace/EKAT_PullRequest_Autotester_Blake
+ '[' 0 -ne 0 ']'
+ FAILED_SP=
+ FAILED_DP=
+ RET_SP=0
+ RET_DP=0
+ mkdir -p ekat-build/ekat-sp
+ cd ekat-build/ekat-sp
+ rm -rf '*'
+ cmake -C /home/e3sm-jenkins/blake/workspace/EKAT_PullRequest_Autotester_Blake/ekat-src/cmake/machine-files/blake.cmake -DCMAKE_INSTALL_PREFIX=/home/e3sm-jenkins/blake/workspace/EKAT_PullRequest_Autotester_Blake/ekat-install/ekat-sp -DCMAKE_BUILD_TYPE=DEBUG -DCMAKE_CXX_COMPILER=mpicxx -DCMAKE_Fortran_COMPILER=mpifort -DEKAT_DISABLE_TPL_WARNINGS=ON -DEKAT_ENABLE_TESTS=ON -DEKAT_TEST_DOUBLE_PRECISION=OFF -DEKAT_TEST_SINGLE_PRECISION=ON /home/e3sm-jenkins/blake/workspace/EKAT_PullRequest_Autotester_Blake/ekat-src
loading initial cache file /home/e3sm-jenkins/blake/workspace/EKAT_PullRequest_Autotester_Blake/ekat-src/cmake/machine-files/blake.cmake
-- The CXX compiler identification is Intel 19.0.0.20181018
-- The Fortran compiler identification is Intel 19.0.0.20181018
-- Check for working CXX compiler: /home/projects/x86-64-skylake/openmpi/2.1.5/intel/19.1.144/bin/mpicxx
-- Check for working CXX compiler: /home/projects/x86-64-skylake/openmpi/2.1.5/intel/19.1.144/bin/mpicxx -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working Fortran compiler: /home/projects/x86-64-skylake/openmpi/2.1.5/intel/19.1.144/bin/mpifort
-- Check for working Fortran compiler: /home/projects/x86-64-skylake/openmpi/2.1.5/intel/19.1.144/bin/mpifort  -- works
-- Detecting Fortran compiler ABI info
-- Detecting Fortran c [...]

2020-09-19 03:10 UTC, E3SM-Autotester commented
Status Flag 'Pre-Test Inspection' - Auto Inspected - Inspection Is Not Necessary for this Pull Request.

2020-09-19 03:13 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: EKAT_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 51</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>EKAT_SOURCE_BRANCH</td>
    <td>PeterCaldwell/add_expm1</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_SHA</td>
    <td>d36b49cf94d055187bc8f246dc1c4dc377ba1de8</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_SHA</td>
    <td>746968a8a524643787c82b344cfc12f8c18d1a12</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;Packs</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>47</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>EKAT</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: EKAT_PullRequest_Autotester_Bowman</h3>
<ul>
  <li>Build Num: 46</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>EKAT_SOURCE_BRANCH</td>
    <td>PeterCaldwell/add_expm1</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_SHA</td>
    <td>d36b49cf94d055187bc8f246dc1c4dc377ba1de8</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_SHA</td>
    <td>746968a8a524643787c82b344cfc12f8c18d1a12</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;Packs</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>47</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>EKAT</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: EKAT_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 50</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>EKAT_SOURCE_BRANCH</td>
    <td>PeterCaldwell/add_expm1</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_SHA</td>
    <td>d36b49cf94d055187bc8f246dc1c4dc377ba1de8</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_SHA</td>
    <td>746968a8a524643787c82b344cfc12f8c18d1a12</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;Packs</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>47</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>EKAT</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: EKAT (E3SM-Project/EKAT)</dt>
  <ul>
    <li>Branch: PeterCaldwell/add_expm1</li>
    <li>SHA: d36b49cf94d055187bc8f246dc1c4dc377ba1de8</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

Pull Request Author: PeterCaldwell
</details>

2020-09-19 13:09 UTC, E3SM-Autotester commented
NOTICE: The AutoTester has encountered an internal error (usually a Communications Timeout), testing will be restarted, previous tests may still be running but will be ignored by the AutoTester...

2020-09-19 13:11 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: EKAT_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 52</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>EKAT_SOURCE_BRANCH</td>
    <td>PeterCaldwell/add_expm1</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_SHA</td>
    <td>d36b49cf94d055187bc8f246dc1c4dc377ba1de8</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_SHA</td>
    <td>746968a8a524643787c82b344cfc12f8c18d1a12</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;Packs</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>47</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>EKAT</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: EKAT_PullRequest_Autotester_Bowman</h3>
<ul>
  <li>Build Num: 47</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>EKAT_SOURCE_BRANCH</td>
    <td>PeterCaldwell/add_expm1</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_SHA</td>
    <td>d36b49cf94d055187bc8f246dc1c4dc377ba1de8</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_SHA</td>
    <td>746968a8a524643787c82b344cfc12f8c18d1a12</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;Packs</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>47</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>EKAT</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: EKAT_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 51</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>EKAT_SOURCE_BRANCH</td>
    <td>PeterCaldwell/add_expm1</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_SHA</td>
    <td>d36b49cf94d055187bc8f246dc1c4dc377ba1de8</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_SHA</td>
    <td>746968a8a524643787c82b344cfc12f8c18d1a12</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;Packs</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>47</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>EKAT</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: EKAT (E3SM-Project/EKAT)</dt>
  <ul>
    <li>Branch: PeterCaldwell/add_expm1</li>
    <li>SHA: d36b49cf94d055187bc8f246dc1c4dc377ba1de8</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

Pull Request Author: PeterCaldwell
</details>

2020-09-19 23:11 UTC, E3SM-Autotester commented
NOTICE: The AutoTester has encountered an internal error (usually a Communications Timeout), testing will be restarted, previous tests may still be running but will be ignored by the AutoTester...

2020-09-19 23:13 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: EKAT_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 53</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>EKAT_SOURCE_BRANCH</td>
    <td>PeterCaldwell/add_expm1</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_SHA</td>
    <td>d36b49cf94d055187bc8f246dc1c4dc377ba1de8</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_SHA</td>
    <td>746968a8a524643787c82b344cfc12f8c18d1a12</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;Packs</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>47</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>EKAT</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: EKAT_PullRequest_Autotester_Bowman</h3>
<ul>
  <li>Build Num: 48</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>EKAT_SOURCE_BRANCH</td>
    <td>PeterCaldwell/add_expm1</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_SHA</td>
    <td>d36b49cf94d055187bc8f246dc1c4dc377ba1de8</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_SHA</td>
    <td>746968a8a524643787c82b344cfc12f8c18d1a12</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;Packs</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>47</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>EKAT</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: EKAT_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 52</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>EKAT_SOURCE_BRANCH</td>
    <td>PeterCaldwell/add_expm1</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_SHA</td>
    <td>d36b49cf94d055187bc8f246dc1c4dc377ba1de8</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_SHA</td>
    <td>746968a8a524643787c82b344cfc12f8c18d1a12</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;Packs</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>47</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>EKAT</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: EKAT (E3SM-Project/EKAT)</dt>
  <ul>
    <li>Branch: PeterCaldwell/add_expm1</li>
    <li>SHA: d36b49cf94d055187bc8f246dc1c4dc377ba1de8</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

Pull Request Author: PeterCaldwell
</details>

2020-09-20 03:04 UTC, E3SM-Autotester commented
NOTICE: The AutoTester has encountered an internal error (usually a Communications Timeout), testing will be restarted, previous tests may still be running but will be ignored by the AutoTester...

2020-09-20 03:07 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: EKAT_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 54</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>EKAT_SOURCE_BRANCH</td>
    <td>PeterCaldwell/add_expm1</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_SHA</td>
    <td>d36b49cf94d055187bc8f246dc1c4dc377ba1de8</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_SHA</td>
    <td>746968a8a524643787c82b344cfc12f8c18d1a12</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;Packs</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>47</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>EKAT</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: EKAT_PullRequest_Autotester_Bowman</h3>
<ul>
  <li>Build Num: 49</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>EKAT_SOURCE_BRANCH</td>
    <td>PeterCaldwell/add_expm1</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_SHA</td>
    <td>d36b49cf94d055187bc8f246dc1c4dc377ba1de8</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_SHA</td>
    <td>746968a8a524643787c82b344cfc12f8c18d1a12</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;Packs</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>47</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>EKAT</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: EKAT_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 53</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>EKAT_SOURCE_BRANCH</td>
    <td>PeterCaldwell/add_expm1</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_SHA</td>
    <td>d36b49cf94d055187bc8f246dc1c4dc377ba1de8</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_SHA</td>
    <td>746968a8a524643787c82b344cfc12f8c18d1a12</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;Packs</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>47</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>EKAT</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: EKAT (E3SM-Project/EKAT)</dt>
  <ul>
    <li>Branch: PeterCaldwell/add_expm1</li>
    <li>SHA: d36b49cf94d055187bc8f246dc1c4dc377ba1de8</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

Pull Request Author: PeterCaldwell
</details>

2020-09-20 04:38 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: 1 or more Jobs FAILED

Note: Testing will normally be attempted again in approx. 4 Hrs. If a change to the PR source branch occurs, the testing will be attempted again on next available autotester run.

<details>
<summary>
  <b>Pull Request Auto Testing has FAILED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: EKAT_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 54</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>EKAT_SOURCE_BRANCH</td>
    <td>PeterCaldwell/add_expm1</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_SHA</td>
    <td>d36b49cf94d055187bc8f246dc1c4dc377ba1de8</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_SHA</td>
    <td>746968a8a524643787c82b344cfc12f8c18d1a12</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;Packs</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>47</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>EKAT</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: EKAT_PullRequest_Autotester_Bowman</h3>
<ul>
  <li>Build Num: 49</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>EKAT_SOURCE_BRANCH</td>
    <td>PeterCaldwell/add_expm1</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_SHA</td>
    <td>d36b49cf94d055187bc8f246dc1c4dc377ba1de8</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_SHA</td>
    <td>746968a8a524643787c82b344cfc12f8c18d1a12</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;Packs</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>47</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>EKAT</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: EKAT_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 53</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>EKAT_SOURCE_BRANCH</td>
    <td>PeterCaldwell/add_expm1</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_SHA</td>
    <td>d36b49cf94d055187bc8f246dc1c4dc377ba1de8</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_SHA</td>
    <td>746968a8a524643787c82b344cfc12f8c18d1a12</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;Packs</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>47</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>EKAT</td>
  </tr>
</table>
</details>


<details>
<summary>
  <b>Console Output (last 100 lines) : EKAT_PullRequest_Autotester_Blake # 54</b> (click to expand)
</summary>
<pre>
<code>
[ 48%] Building CXX object externals/kokkos/core/src/CMakeFiles/kokkoscore.dir/impl/Kokkos_SharedAlloc.cpp.o
[ 48%] Building CXX object externals/kokkos/core/src/CMakeFiles/kokkoscore.dir/impl/Kokkos_Profiling_Interface.cpp.o
[ 48%] Building CXX object externals/kokkos/core/src/CMakeFiles/kokkoscore.dir/impl/Kokkos_Stacktrace.cpp.o
[ 48%] Building CXX object externals/kokkos/core/src/CMakeFiles/kokkoscore.dir/impl/Kokkos_Spinwait.cpp.o
[ 48%] Building CXX object externals/kokkos/core/src/CMakeFiles/kokkoscore.dir/impl/Kokkos_hwloc.cpp.o
[ 48%] Building CXX object externals/kokkos/core/src/CMakeFiles/kokkoscore.dir/OpenMP/Kokkos_OpenMP_Task.cpp.o
[ 49%] Linking CXX static library libyaml-cppd.a
[ 49%] Built target yaml-cpp
[ 50%] Linking CXX static library libkokkoscore.a
[ 50%] Built target kokkoscore
Scanning dependencies of target kokkoscontainers
[ 51%] Building CXX object externals/kokkos/containers/src/CMakeFiles/kokkoscontainers.dir/impl/Kokkos_UnorderedMap_impl.cpp.o
[ 52%] Linking CXX static library libkokkoscontainers.a
[ 52%] Built target kokkoscontainers
Scanning dependencies of target ekat
[ 53%] Building Fortran object src/ekat/CMakeFiles/ekat.dir/util/ekat_array_io_mod.f90.o
[ 54%] Building CXX object src/ekat/CMakeFiles/ekat.dir/ekat_assert.cpp.o
[ 56%] Building CXX object src/ekat/CMakeFiles/ekat.dir/ekat_parameter_list.cpp.o
[ 56%] Building CXX object src/ekat/CMakeFiles/ekat.dir/ekat_parse_yaml_file.cpp.o
[ 57%] Building CXX object src/ekat/CMakeFiles/ekat.dir/ekat_session.cpp.o
[ 58%] Building CXX object src/ekat/CMakeFiles/ekat.dir/mpi/ekat_comm.cpp.o
[ 62%] Building CXX object src/ekat/CMakeFiles/ekat.dir/util/ekat_arch.cpp.o
[ 62%] Building CXX object src/ekat/CMakeFiles/ekat.dir/util/ekat_array_io.cpp.o
[ 62%] Building CXX object src/ekat/CMakeFiles/ekat.dir/util/ekat_string_utils.cpp.o
[ 62%] Building CXX object src/ekat/CMakeFiles/ekat.dir/util/ekat_test_utils.cpp.o
[ 63%] Linking CXX static library libekat.a
[ 63%] Built target ekat
Scanning dependencies of target ekat_test_session
[ 64%] Building CXX object src/ekat/CMakeFiles/ekat_test_session.dir/util/ekat_test_session.cpp.o
Scanning dependencies of target ekat_test_main
[ 65%] Building CXX object src/ekat/CMakeFiles/ekat_test_main.dir/util/ekat_catch_main.cpp.o
[ 67%] Linking CXX static library libekat_test_session.a
[ 67%] Built target ekat_test_session
Scanning dependencies of target tridiag
[ 68%] Building Fortran object tests/algorithm/CMakeFiles/tridiag.dir/tridiag_bfb_mod.F90.o
[ 72%] Building CXX object tests/algorithm/CMakeFiles/tridiag.dir/tridiag_bfb.cpp.o
[ 72%] Building CXX object tests/algorithm/CMakeFiles/tridiag.dir/tridiag_tests.cpp.o
[ 72%] Building CXX object tests/algorithm/CMakeFiles/tridiag.dir/tridiag_tests_performance.cpp.o
[ 72%] Building CXX object tests/algorithm/CMakeFiles/tridiag.dir/tridiag_tests_correctness.cpp.o
[ 73%] Linking CXX static library libekat_test_main.a
[ 74%] Linking CXX executable tridiag
[ 74%] Built target ekat_test_main
Scanning dependencies of target debug_tools
Scanning dependencies of target yaml_parser
Scanning dependencies of target units
[ 75%] Building CXX object tests/utils/CMakeFiles/debug_tools.dir/debug_tools_tests.cpp.o
[ 77%] Building CXX object tests/units/CMakeFiles/units.dir/units.cpp.o
[ 77%] Building CXX object tests/io/CMakeFiles/yaml_parser.dir/yaml_parser.cpp.o
Scanning dependencies of target lin_interp
Scanning dependencies of target pack_utils
Scanning dependencies of target upper_bound
[ 78%] Building Fortran object tests/algorithm/CMakeFiles/lin_interp.dir/lin_interp_ref.f90.o
Scanning dependencies of target util_cxx
Scanning dependencies of target wsm
Scanning dependencies of target array_io
Scanning dependencies of target packs
Scanning dependencies of target kokkos_utils
[ 79%] Building CXX object tests/algorithm/CMakeFiles/lin_interp.dir/lin_interp_test.cpp.o
[ 82%] Building CXX object tests/utils/CMakeFiles/upper_bound.dir/upper_bound_test.cpp.o
[ 82%] Building Fortran object tests/io/CMakeFiles/array_io.dir/array_io_tests.f90.o
[ 82%] Building CXX object tests/utils/CMakeFiles/util_cxx.dir/util_tests.cpp.o
[ 86%] Building CXX object tests/pack/CMakeFiles/pack_utils.dir/pack_utils_tests.cpp.o
[ 88%] Building CXX object tests/io/CMakeFiles/array_io.dir/array_io_tests.cpp.o
[ 88%] Building CXX object tests/pack/CMakeFiles/packs.dir/pack_tests.cpp.o
[ 88%] Building CXX object tests/kokkos/CMakeFiles/kokkos_utils.dir/kokkos_utils_tests.cpp.o
[ 88%] Building CXX object tests/pack/C [...]

2020-09-20 15:27 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: EKAT_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 57</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>EKAT_SOURCE_BRANCH</td>
    <td>PeterCaldwell/add_expm1</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_SHA</td>
    <td>d36b49cf94d055187bc8f246dc1c4dc377ba1de8</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_SHA</td>
    <td>746968a8a524643787c82b344cfc12f8c18d1a12</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;Packs</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>47</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>EKAT</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: EKAT_PullRequest_Autotester_Bowman</h3>
<ul>
  <li>Build Num: 52</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>EKAT_SOURCE_BRANCH</td>
    <td>PeterCaldwell/add_expm1</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_SHA</td>
    <td>d36b49cf94d055187bc8f246dc1c4dc377ba1de8</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_SHA</td>
    <td>746968a8a524643787c82b344cfc12f8c18d1a12</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;Packs</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>47</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>EKAT</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: EKAT_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 56</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>EKAT_SOURCE_BRANCH</td>
    <td>PeterCaldwell/add_expm1</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_SHA</td>
    <td>d36b49cf94d055187bc8f246dc1c4dc377ba1de8</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_SHA</td>
    <td>746968a8a524643787c82b344cfc12f8c18d1a12</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;Packs</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>47</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>EKAT</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: EKAT (E3SM-Project/EKAT)</dt>
  <ul>
    <li>Branch: PeterCaldwell/add_expm1</li>
    <li>SHA: d36b49cf94d055187bc8f246dc1c4dc377ba1de8</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

Pull Request Author: PeterCaldwell
</details>

2020-09-20 16:58 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: 1 or more Jobs FAILED

Note: Testing will normally be attempted again in approx. 4 Hrs. If a change to the PR source branch occurs, the testing will be attempted again on next available autotester run.

<details>
<summary>
  <b>Pull Request Auto Testing has FAILED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: EKAT_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 57</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>EKAT_SOURCE_BRANCH</td>
    <td>PeterCaldwell/add_expm1</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_SHA</td>
    <td>d36b49cf94d055187bc8f246dc1c4dc377ba1de8</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_SHA</td>
    <td>746968a8a524643787c82b344cfc12f8c18d1a12</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;Packs</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>47</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>EKAT</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: EKAT_PullRequest_Autotester_Bowman</h3>
<ul>
  <li>Build Num: 52</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>EKAT_SOURCE_BRANCH</td>
    <td>PeterCaldwell/add_expm1</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_SHA</td>
    <td>d36b49cf94d055187bc8f246dc1c4dc377ba1de8</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_SHA</td>
    <td>746968a8a524643787c82b344cfc12f8c18d1a12</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;Packs</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>47</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>EKAT</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: EKAT_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 56</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>EKAT_SOURCE_BRANCH</td>
    <td>PeterCaldwell/add_expm1</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_SHA</td>
    <td>d36b49cf94d055187bc8f246dc1c4dc377ba1de8</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_SHA</td>
    <td>746968a8a524643787c82b344cfc12f8c18d1a12</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;Packs</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>47</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>EKAT</td>
  </tr>
</table>
</details>


<details>
<summary>
  <b>Console Output (last 100 lines) : EKAT_PullRequest_Autotester_Blake # 57</b> (click to expand)
</summary>
<pre>
<code>
[ 45%] Building CXX object externals/kokkos/core/src/CMakeFiles/kokkoscore.dir/impl/Kokkos_Profiling_Interface.cpp.o
[ 48%] Building CXX object externals/kokkos/core/src/CMakeFiles/kokkoscore.dir/impl/Kokkos_hwloc.cpp.o
[ 48%] Building CXX object externals/kokkos/core/src/CMakeFiles/kokkoscore.dir/OpenMP/Kokkos_OpenMP_Exec.cpp.o
[ 48%] Building CXX object externals/kokkos/core/src/CMakeFiles/kokkoscore.dir/OpenMP/Kokkos_OpenMP_Task.cpp.o
[ 48%] Building CXX object externals/kokkos/core/src/CMakeFiles/kokkoscore.dir/impl/Kokkos_SharedAlloc.cpp.o
[ 48%] Building CXX object externals/kokkos/core/src/CMakeFiles/kokkoscore.dir/impl/Kokkos_Stacktrace.cpp.o
[ 49%] Linking CXX static library libyaml-cppd.a
[ 49%] Built target yaml-cpp
[ 50%] Linking CXX static library libkokkoscore.a
[ 50%] Built target kokkoscore
Scanning dependencies of target kokkoscontainers
[ 51%] Building CXX object externals/kokkos/containers/src/CMakeFiles/kokkoscontainers.dir/impl/Kokkos_UnorderedMap_impl.cpp.o
[ 52%] Linking CXX static library libkokkoscontainers.a
[ 52%] Built target kokkoscontainers
Scanning dependencies of target ekat
[ 53%] Building Fortran object src/ekat/CMakeFiles/ekat.dir/util/ekat_array_io_mod.f90.o
[ 54%] Building CXX object src/ekat/CMakeFiles/ekat.dir/ekat_assert.cpp.o
[ 56%] Building CXX object src/ekat/CMakeFiles/ekat.dir/ekat_parameter_list.cpp.o
[ 56%] Building CXX object src/ekat/CMakeFiles/ekat.dir/ekat_parse_yaml_file.cpp.o
[ 57%] Building CXX object src/ekat/CMakeFiles/ekat.dir/ekat_session.cpp.o
[ 58%] Building CXX object src/ekat/CMakeFiles/ekat.dir/mpi/ekat_comm.cpp.o
[ 60%] Building CXX object src/ekat/CMakeFiles/ekat.dir/util/ekat_arch.cpp.o
[ 61%] Building CXX object src/ekat/CMakeFiles/ekat.dir/util/ekat_array_io.cpp.o
[ 61%] Building CXX object src/ekat/CMakeFiles/ekat.dir/util/ekat_string_utils.cpp.o
[ 62%] Building CXX object src/ekat/CMakeFiles/ekat.dir/util/ekat_test_utils.cpp.o
[ 63%] Linking CXX static library libekat.a
[ 63%] Built target ekat
Scanning dependencies of target ekat_test_session
[ 64%] Building CXX object src/ekat/CMakeFiles/ekat_test_session.dir/util/ekat_test_session.cpp.o
[ 65%] Linking CXX static library libekat_test_session.a
[ 65%] Built target ekat_test_session
Scanning dependencies of target ekat_test_main
[ 67%] Building CXX object src/ekat/CMakeFiles/ekat_test_main.dir/util/ekat_catch_main.cpp.o
Scanning dependencies of target tridiag
[ 68%] Building Fortran object tests/algorithm/CMakeFiles/tridiag.dir/tridiag_bfb_mod.F90.o
[ 70%] Building CXX object tests/algorithm/CMakeFiles/tridiag.dir/tridiag_tests.cpp.o
[ 71%] Building CXX object tests/algorithm/CMakeFiles/tridiag.dir/tridiag_tests_correctness.cpp.o
[ 71%] Building CXX object tests/algorithm/CMakeFiles/tridiag.dir/tridiag_bfb.cpp.o
[ 72%] Building CXX object tests/algorithm/CMakeFiles/tridiag.dir/tridiag_tests_performance.cpp.o
[ 73%] Linking CXX static library libekat_test_main.a
[ 74%] Linking CXX executable tridiag
[ 74%] Built target tridiag
[ 74%] Built target ekat_test_main
Scanning dependencies of target debug_tools
Scanning dependencies of target units
Scanning dependencies of target yaml_parser
[ 75%] Building CXX object tests/utils/CMakeFiles/debug_tools.dir/debug_tools_tests.cpp.o
[ 76%] Building CXX object tests/units/CMakeFiles/units.dir/units.cpp.o
[ 77%] Building CXX object tests/io/CMakeFiles/yaml_parser.dir/yaml_parser.cpp.o
Scanning dependencies of target lin_interp
Scanning dependencies of target util_cxx
Scanning dependencies of target wsm
Scanning dependencies of target kokkos_utils
Scanning dependencies of target pack_utils
Scanning dependencies of target upper_bound
Scanning dependencies of target array_io
Scanning dependencies of target packs
[ 78%] Building Fortran object tests/algorithm/CMakeFiles/lin_interp.dir/lin_interp_ref.f90.o
[ 79%] Building CXX object tests/algorithm/CMakeFiles/lin_interp.dir/lin_interp_test.cpp.o
[ 80%] Building CXX object tests/utils/CMakeFiles/util_cxx.dir/util_tests.cpp.o
[ 85%] Building CXX object tests/utils/CMakeFiles/upper_bound.dir/upper_bound_test.cpp.o
[ 85%] Building CXX object tests/kokkos/CMakeFiles/kokkos_utils.dir/kokkos_utils_tests.cpp.o
[ 85%] Building CXX object tests/kokkos/CMakeFiles/wsm.dir/workspace_tests.cpp.o
[ 85%] Building Fortran object tests/io/CMakeFiles/array_io.dir/array_io_tests.f90.o
[ 85%] Building CXX object tests/pack/CMakeFiles/pack_utils.dir/pack_utils_tests.cpp.o
[ 88%] Building CXX object tests/pack/CMakeFiles/packs.dir/pack_kokkos_tests.cpp.o [...]

2020-09-21 07:16 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: EKAT_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 59</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>EKAT_SOURCE_BRANCH</td>
    <td>PeterCaldwell/add_expm1</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_SHA</td>
    <td>d36b49cf94d055187bc8f246dc1c4dc377ba1de8</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_SHA</td>
    <td>746968a8a524643787c82b344cfc12f8c18d1a12</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;Packs</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>47</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>EKAT</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: EKAT_PullRequest_Autotester_Bowman</h3>
<ul>
  <li>Build Num: 54</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>EKAT_SOURCE_BRANCH</td>
    <td>PeterCaldwell/add_expm1</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_SHA</td>
    <td>d36b49cf94d055187bc8f246dc1c4dc377ba1de8</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_SHA</td>
    <td>746968a8a524643787c82b344cfc12f8c18d1a12</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;Packs</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>47</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>EKAT</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: EKAT_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 58</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>EKAT_SOURCE_BRANCH</td>
    <td>PeterCaldwell/add_expm1</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_SHA</td>
    <td>d36b49cf94d055187bc8f246dc1c4dc377ba1de8</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_SHA</td>
    <td>746968a8a524643787c82b344cfc12f8c18d1a12</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;Packs</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>47</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>EKAT</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: EKAT (E3SM-Project/EKAT)</dt>
  <ul>
    <li>Branch: PeterCaldwell/add_expm1</li>
    <li>SHA: d36b49cf94d055187bc8f246dc1c4dc377ba1de8</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

Pull Request Author: PeterCaldwell
</details>

2020-09-21 07:59 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Failure: Timed out waiting for job EKAT_PullRequest_Autotester_Blake to start: Total Wait = 1803
- Other jobs have been previously started - We must stop them...

2020-09-21 12:04 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: EKAT_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 60</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>EKAT_SOURCE_BRANCH</td>
    <td>PeterCaldwell/add_expm1</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_SHA</td>
    <td>d36b49cf94d055187bc8f246dc1c4dc377ba1de8</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_SHA</td>
    <td>746968a8a524643787c82b344cfc12f8c18d1a12</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;Packs</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>47</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>EKAT</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: EKAT_PullRequest_Autotester_Bowman</h3>
<ul>
  <li>Build Num: 55</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>EKAT_SOURCE_BRANCH</td>
    <td>PeterCaldwell/add_expm1</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_SHA</td>
    <td>d36b49cf94d055187bc8f246dc1c4dc377ba1de8</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_SHA</td>
    <td>746968a8a524643787c82b344cfc12f8c18d1a12</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;Packs</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>47</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>EKAT</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: EKAT_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 59</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>EKAT_SOURCE_BRANCH</td>
    <td>PeterCaldwell/add_expm1</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_SHA</td>
    <td>d36b49cf94d055187bc8f246dc1c4dc377ba1de8</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_SHA</td>
    <td>746968a8a524643787c82b344cfc12f8c18d1a12</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;Packs</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>47</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>EKAT</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: EKAT (E3SM-Project/EKAT)</dt>
  <ul>
    <li>Branch: PeterCaldwell/add_expm1</li>
    <li>SHA: d36b49cf94d055187bc8f246dc1c4dc377ba1de8</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

Pull Request Author: PeterCaldwell
</details>

2020-09-21 13:35 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: 1 or more Jobs FAILED

Note: Testing will normally be attempted again in approx. 4 Hrs. If a change to the PR source branch occurs, the testing will be attempted again on next available autotester run.

<details>
<summary>
  <b>Pull Request Auto Testing has FAILED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: EKAT_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 60</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>EKAT_SOURCE_BRANCH</td>
    <td>PeterCaldwell/add_expm1</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_SHA</td>
    <td>d36b49cf94d055187bc8f246dc1c4dc377ba1de8</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_SHA</td>
    <td>746968a8a524643787c82b344cfc12f8c18d1a12</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;Packs</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>47</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>EKAT</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: EKAT_PullRequest_Autotester_Bowman</h3>
<ul>
  <li>Build Num: 55</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>EKAT_SOURCE_BRANCH</td>
    <td>PeterCaldwell/add_expm1</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_SHA</td>
    <td>d36b49cf94d055187bc8f246dc1c4dc377ba1de8</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_SHA</td>
    <td>746968a8a524643787c82b344cfc12f8c18d1a12</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;Packs</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>47</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>EKAT</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: EKAT_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 59</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>EKAT_SOURCE_BRANCH</td>
    <td>PeterCaldwell/add_expm1</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_SHA</td>
    <td>d36b49cf94d055187bc8f246dc1c4dc377ba1de8</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_SHA</td>
    <td>746968a8a524643787c82b344cfc12f8c18d1a12</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;Packs</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>47</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>EKAT</td>
  </tr>
</table>
</details>


<details>
<summary>
  <b>Console Output (last 100 lines) : EKAT_PullRequest_Autotester_Blake # 60</b> (click to expand)
</summary>
<pre>
<code>
[ 48%] Building CXX object externals/kokkos/core/src/CMakeFiles/kokkoscore.dir/impl/Kokkos_Core.cpp.o
[ 48%] Building CXX object externals/kokkos/core/src/CMakeFiles/kokkoscore.dir/impl/Kokkos_Serial_Task.cpp.o
[ 48%] Building CXX object externals/kokkos/core/src/CMakeFiles/kokkoscore.dir/impl/Kokkos_ExecPolicy.cpp.o
[ 48%] Building CXX object externals/kokkos/core/src/CMakeFiles/kokkoscore.dir/impl/Kokkos_Stacktrace.cpp.o
[ 48%] Building CXX object externals/kokkos/core/src/CMakeFiles/kokkoscore.dir/OpenMP/Kokkos_OpenMP_Exec.cpp.o
[ 48%] Building CXX object externals/kokkos/core/src/CMakeFiles/kokkoscore.dir/OpenMP/Kokkos_OpenMP_Task.cpp.o
[ 48%] Building CXX object externals/kokkos/core/src/CMakeFiles/kokkoscore.dir/impl/Kokkos_hwloc.cpp.o
[ 48%] Building CXX object externals/kokkos/core/src/CMakeFiles/kokkoscore.dir/impl/Kokkos_Spinwait.cpp.o
[ 49%] Linking CXX static library libyaml-cppd.a
[ 49%] Built target yaml-cpp
[ 50%] Linking CXX static library libkokkoscore.a
[ 50%] Built target kokkoscore
Scanning dependencies of target kokkoscontainers
[ 51%] Building CXX object externals/kokkos/containers/src/CMakeFiles/kokkoscontainers.dir/impl/Kokkos_UnorderedMap_impl.cpp.o
[ 52%] Linking CXX static library libkokkoscontainers.a
[ 52%] Built target kokkoscontainers
Scanning dependencies of target ekat
[ 53%] Building Fortran object src/ekat/CMakeFiles/ekat.dir/util/ekat_array_io_mod.f90.o
[ 55%] Building CXX object src/ekat/CMakeFiles/ekat.dir/ekat_assert.cpp.o
[ 55%] Building CXX object src/ekat/CMakeFiles/ekat.dir/ekat_parameter_list.cpp.o
[ 56%] Building CXX object src/ekat/CMakeFiles/ekat.dir/ekat_parse_yaml_file.cpp.o
[ 57%] Building CXX object src/ekat/CMakeFiles/ekat.dir/ekat_session.cpp.o
[ 58%] Building CXX object src/ekat/CMakeFiles/ekat.dir/mpi/ekat_comm.cpp.o
[ 59%] Building CXX object src/ekat/CMakeFiles/ekat.dir/util/ekat_arch.cpp.o
[ 60%] Building CXX object src/ekat/CMakeFiles/ekat.dir/util/ekat_array_io.cpp.o
[ 62%] Building CXX object src/ekat/CMakeFiles/ekat.dir/util/ekat_string_utils.cpp.o
[ 62%] Building CXX object src/ekat/CMakeFiles/ekat.dir/util/ekat_test_utils.cpp.o
[ 63%] Linking CXX static library libekat.a
[ 63%] Built target ekat
Scanning dependencies of target ekat_test_session
[ 64%] Building CXX object src/ekat/CMakeFiles/ekat_test_session.dir/util/ekat_test_session.cpp.o
[ 65%] Linking CXX static library libekat_test_session.a
[ 65%] Built target ekat_test_session
Scanning dependencies of target ekat_test_main
[ 67%] Building CXX object src/ekat/CMakeFiles/ekat_test_main.dir/util/ekat_catch_main.cpp.o
Scanning dependencies of target tridiag
[ 68%] Building Fortran object tests/algorithm/CMakeFiles/tridiag.dir/tridiag_bfb_mod.F90.o
[ 70%] Building CXX object tests/algorithm/CMakeFiles/tridiag.dir/tridiag_tests.cpp.o
[ 71%] Building CXX object tests/algorithm/CMakeFiles/tridiag.dir/tridiag_bfb.cpp.o
[ 72%] Building CXX object tests/algorithm/CMakeFiles/tridiag.dir/tridiag_tests_correctness.cpp.o
[ 72%] Building CXX object tests/algorithm/CMakeFiles/tridiag.dir/tridiag_tests_performance.cpp.o
[ 73%] Linking CXX static library libekat_test_main.a
[ 74%] Linking CXX executable tridiag
[ 74%] Built target ekat_test_main
Scanning dependencies of target debug_tools
Scanning dependencies of target units
Scanning dependencies of target yaml_parser
[ 75%] Building CXX object tests/utils/CMakeFiles/debug_tools.dir/debug_tools_tests.cpp.o
[ 76%] Building CXX object tests/units/CMakeFiles/units.dir/units.cpp.o
[ 77%] Building CXX object tests/io/CMakeFiles/yaml_parser.dir/yaml_parser.cpp.o
Scanning dependencies of target lin_interp
Scanning dependencies of target pack_utils
Scanning dependencies of target upper_bound
Scanning dependencies of target util_cxx
[ 78%] Building Fortran object tests/algorithm/CMakeFiles/lin_interp.dir/lin_interp_ref.f90.o
Scanning dependencies of target packs
[ 79%] Building CXX object tests/algorithm/CMakeFiles/lin_interp.dir/lin_interp_test.cpp.o
Scanning dependencies of target kokkos_utils
Scanning dependencies of target wsm
[ 80%] Building CXX object tests/pack/CMakeFiles/pack_utils.dir/pack_utils_tests.cpp.o
[ 81%] Building CXX object tests/utils/CMakeFiles/upper_bound.dir/upper_bound_test.cpp.o
Scanning dependencies of target array_io
[ 82%] Building CXX object tests/utils/CMakeFiles/util_cxx.dir/util_tests.cpp.o
[ 84%] Building CXX object tests/pack/CMakeFiles/packs.dir/pack_tests.cpp.o
[ 84%] Building CXX object tests/pack/CMakeFiles/packs.dir/pack_kokkos_tests.cpp.o
[ 86%] Buil [...]

2020-09-21 19:16 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: EKAT_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 62</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>EKAT_SOURCE_BRANCH</td>
    <td>PeterCaldwell/add_expm1</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_SHA</td>
    <td>d36b49cf94d055187bc8f246dc1c4dc377ba1de8</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_SHA</td>
    <td>746968a8a524643787c82b344cfc12f8c18d1a12</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;Packs</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>47</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>EKAT</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: EKAT_PullRequest_Autotester_Bowman</h3>
<ul>
  <li>Build Num: 57</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>EKAT_SOURCE_BRANCH</td>
    <td>PeterCaldwell/add_expm1</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_SHA</td>
    <td>d36b49cf94d055187bc8f246dc1c4dc377ba1de8</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_SHA</td>
    <td>746968a8a524643787c82b344cfc12f8c18d1a12</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;Packs</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>47</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>EKAT</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: EKAT_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 61</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>EKAT_SOURCE_BRANCH</td>
    <td>PeterCaldwell/add_expm1</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_SHA</td>
    <td>d36b49cf94d055187bc8f246dc1c4dc377ba1de8</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_SHA</td>
    <td>746968a8a524643787c82b344cfc12f8c18d1a12</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;Packs</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>47</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>EKAT</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: EKAT (E3SM-Project/EKAT)</dt>
  <ul>
    <li>Branch: PeterCaldwell/add_expm1</li>
    <li>SHA: d36b49cf94d055187bc8f246dc1c4dc377ba1de8</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

Pull Request Author: PeterCaldwell
</details>

2020-09-21 20:48 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: 1 or more Jobs FAILED

Note: Testing will normally be attempted again in approx. 4 Hrs. If a change to the PR source branch occurs, the testing will be attempted again on next available autotester run.

<details>
<summary>
  <b>Pull Request Auto Testing has FAILED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: EKAT_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 62</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>EKAT_SOURCE_BRANCH</td>
    <td>PeterCaldwell/add_expm1</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_SHA</td>
    <td>d36b49cf94d055187bc8f246dc1c4dc377ba1de8</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_SHA</td>
    <td>746968a8a524643787c82b344cfc12f8c18d1a12</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;Packs</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>47</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>EKAT</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: EKAT_PullRequest_Autotester_Bowman</h3>
<ul>
  <li>Build Num: 57</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>EKAT_SOURCE_BRANCH</td>
    <td>PeterCaldwell/add_expm1</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_SHA</td>
    <td>d36b49cf94d055187bc8f246dc1c4dc377ba1de8</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_SHA</td>
    <td>746968a8a524643787c82b344cfc12f8c18d1a12</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;Packs</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>47</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>EKAT</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: EKAT_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 61</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>EKAT_SOURCE_BRANCH</td>
    <td>PeterCaldwell/add_expm1</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_SHA</td>
    <td>d36b49cf94d055187bc8f246dc1c4dc377ba1de8</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_SHA</td>
    <td>746968a8a524643787c82b344cfc12f8c18d1a12</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;Packs</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>47</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>EKAT</td>
  </tr>
</table>
</details>


<details>
<summary>
  <b>Console Output (last 100 lines) : EKAT_PullRequest_Autotester_Blake # 62</b> (click to expand)
</summary>
<pre>
<code>
[ 42%] Building CXX object externals/kokkos/core/src/CMakeFiles/kokkoscore.dir/impl/Kokkos_Serial_Task.cpp.o
[ 45%] Building CXX object externals/kokkos/core/src/CMakeFiles/kokkoscore.dir/impl/Kokkos_SharedAlloc.cpp.o
[ 46%] Building CXX object externals/kokkos/core/src/CMakeFiles/kokkoscore.dir/impl/Kokkos_Spinwait.cpp.o
[ 46%] Building CXX object externals/kokkos/core/src/CMakeFiles/kokkoscore.dir/impl/Kokkos_Stacktrace.cpp.o
[ 48%] Building CXX object externals/kokkos/core/src/CMakeFiles/kokkoscore.dir/OpenMP/Kokkos_OpenMP_Task.cpp.o
[ 48%] Building CXX object externals/kokkos/core/src/CMakeFiles/kokkoscore.dir/impl/Kokkos_hwloc.cpp.o
[ 48%] Building CXX object externals/kokkos/core/src/CMakeFiles/kokkoscore.dir/OpenMP/Kokkos_OpenMP_Exec.cpp.o
[ 49%] Linking CXX static library libyaml-cppd.a
[ 49%] Built target yaml-cpp
[ 50%] Linking CXX static library libkokkoscore.a
[ 50%] Built target kokkoscore
Scanning dependencies of target kokkoscontainers
[ 51%] Building CXX object externals/kokkos/containers/src/CMakeFiles/kokkoscontainers.dir/impl/Kokkos_UnorderedMap_impl.cpp.o
[ 52%] Linking CXX static library libkokkoscontainers.a
[ 52%] Built target kokkoscontainers
Scanning dependencies of target ekat
[ 53%] Building Fortran object src/ekat/CMakeFiles/ekat.dir/util/ekat_array_io_mod.f90.o
[ 56%] Building CXX object src/ekat/CMakeFiles/ekat.dir/ekat_assert.cpp.o
[ 56%] Building CXX object src/ekat/CMakeFiles/ekat.dir/ekat_parameter_list.cpp.o
[ 56%] Building CXX object src/ekat/CMakeFiles/ekat.dir/ekat_parse_yaml_file.cpp.o
[ 57%] Building CXX object src/ekat/CMakeFiles/ekat.dir/ekat_session.cpp.o
[ 58%] Building CXX object src/ekat/CMakeFiles/ekat.dir/mpi/ekat_comm.cpp.o
[ 61%] Building CXX object src/ekat/CMakeFiles/ekat.dir/util/ekat_arch.cpp.o
[ 61%] Building CXX object src/ekat/CMakeFiles/ekat.dir/util/ekat_array_io.cpp.o
[ 62%] Building CXX object src/ekat/CMakeFiles/ekat.dir/util/ekat_string_utils.cpp.o
[ 62%] Building CXX object src/ekat/CMakeFiles/ekat.dir/util/ekat_test_utils.cpp.o
[ 63%] Linking CXX static library libekat.a
[ 63%] Built target ekat
Scanning dependencies of target ekat_test_session
[ 64%] Building CXX object src/ekat/CMakeFiles/ekat_test_session.dir/util/ekat_test_session.cpp.o
[ 65%] Linking CXX static library libekat_test_session.a
[ 65%] Built target ekat_test_session
Scanning dependencies of target ekat_test_main
[ 67%] Building CXX object src/ekat/CMakeFiles/ekat_test_main.dir/util/ekat_catch_main.cpp.o
Scanning dependencies of target tridiag
[ 68%] Building Fortran object tests/algorithm/CMakeFiles/tridiag.dir/tridiag_bfb_mod.F90.o
[ 72%] Building CXX object tests/algorithm/CMakeFiles/tridiag.dir/tridiag_bfb.cpp.o
[ 72%] Building CXX object tests/algorithm/CMakeFiles/tridiag.dir/tridiag_tests_correctness.cpp.o
[ 72%] Building CXX object tests/algorithm/CMakeFiles/tridiag.dir/tridiag_tests.cpp.o
[ 72%] Building CXX object tests/algorithm/CMakeFiles/tridiag.dir/tridiag_tests_performance.cpp.o
[ 73%] Linking CXX executable tridiag
[ 74%] Linking CXX static library libekat_test_main.a
[ 74%] Built target tridiag
[ 74%] Built target ekat_test_main
Scanning dependencies of target yaml_parser
Scanning dependencies of target units
[ 75%] Building CXX object tests/io/CMakeFiles/yaml_parser.dir/yaml_parser.cpp.o
[ 76%] Building CXX object tests/units/CMakeFiles/units.dir/units.cpp.o
Scanning dependencies of target debug_tools
[ 77%] Building CXX object tests/utils/CMakeFiles/debug_tools.dir/debug_tools_tests.cpp.o
Scanning dependencies of target lin_interp
Scanning dependencies of target wsm
Scanning dependencies of target kokkos_utils
Scanning dependencies of target array_io
[ 78%] Building Fortran object tests/algorithm/CMakeFiles/lin_interp.dir/lin_interp_ref.f90.o
[ 79%] Building CXX object tests/algorithm/CMakeFiles/lin_interp.dir/lin_interp_test.cpp.o
[ 81%] Building CXX object tests/kokkos/CMakeFiles/wsm.dir/workspace_tests.cpp.o
[ 82%] Building CXX object tests/kokkos/CMakeFiles/kokkos_utils.dir/kokkos_utils_tests.cpp.o
[ 82%] Building Fortran object tests/io/CMakeFiles/array_io.dir/array_io_tests.f90.o
Scanning dependencies of target upper_bound
Scanning dependencies of target util_cxx
Scanning dependencies of target pack_utils
[ 83%] Building CXX object tests/io/CMakeFiles/array_io.dir/array_io_tests.cpp.o
Scanning dependencies of target packs
[ 84%] Building CXX object tests/utils/CMakeFiles/upper_bound.dir/upper_bound_test.cpp.o
[ 85%] Building CXX object tests/utils/CMakeFiles/util_cxx.dir/util_te [...]

2020-09-22 19:02 UTC, E3SM-Autotester commented
Status Flag 'Pre-Test Inspection' - Auto Inspected - Inspection Is Not Necessary for this Pull Request.

2020-09-22 19:08 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: EKAT_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 65</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>EKAT_SOURCE_BRANCH</td>
    <td>PeterCaldwell/add_expm1</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_SHA</td>
    <td>6057eb1285c61a3580d423a50844e1d4ef4c26bd</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_SHA</td>
    <td>746968a8a524643787c82b344cfc12f8c18d1a12</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;Packs</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>47</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>EKAT</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: EKAT_PullRequest_Autotester_Bowman</h3>
<ul>
  <li>Build Num: 60</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>EKAT_SOURCE_BRANCH</td>
    <td>PeterCaldwell/add_expm1</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_SHA</td>
    <td>6057eb1285c61a3580d423a50844e1d4ef4c26bd</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_SHA</td>
    <td>746968a8a524643787c82b344cfc12f8c18d1a12</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;Packs</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>47</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>EKAT</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: EKAT_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 64</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>EKAT_SOURCE_BRANCH</td>
    <td>PeterCaldwell/add_expm1</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_SHA</td>
    <td>6057eb1285c61a3580d423a50844e1d4ef4c26bd</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_SHA</td>
    <td>746968a8a524643787c82b344cfc12f8c18d1a12</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;Packs</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>47</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>EKAT</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: EKAT (E3SM-Project/EKAT)</dt>
  <ul>
    <li>Branch: PeterCaldwell/add_expm1</li>
    <li>SHA: 6057eb1285c61a3580d423a50844e1d4ef4c26bd</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

Pull Request Author: PeterCaldwell
</details>

2020-09-22 20:02 UTC, merged

2020-09-22 20:03 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Error: Jenkins Jobs - A user has closed the PR before testing completed.  The Jenkins Jobs will be shutdown

2020-09-22 20:04 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: 1 or more Jobs FAILED

Note: Testing will normally be attempted again in approx. 4 Hrs. If a change to the PR source branch occurs, the testing will be attempted again on next available autotester run.

<details>
<summary>
  <b>Pull Request Auto Testing has FAILED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: EKAT_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 65</li>
  <li>Status: ERROR</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>EKAT_SOURCE_BRANCH</td>
    <td>PeterCaldwell/add_expm1</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_SHA</td>
    <td>6057eb1285c61a3580d423a50844e1d4ef4c26bd</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_SHA</td>
    <td>746968a8a524643787c82b344cfc12f8c18d1a12</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;Packs</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>47</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>EKAT</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: EKAT_PullRequest_Autotester_Bowman</h3>
<ul>
  <li>Build Num: 60</li>
  <li>Status: ERROR</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>EKAT_SOURCE_BRANCH</td>
    <td>PeterCaldwell/add_expm1</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_SHA</td>
    <td>6057eb1285c61a3580d423a50844e1d4ef4c26bd</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_SHA</td>
    <td>746968a8a524643787c82b344cfc12f8c18d1a12</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;Packs</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>47</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>EKAT</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: EKAT_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 64</li>
  <li>Status: ERROR</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>EKAT_SOURCE_BRANCH</td>
    <td>PeterCaldwell/add_expm1</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_SOURCE_SHA</td>
    <td>6057eb1285c61a3580d423a50844e1d4ef4c26bd</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/EKAT</td>
  </tr>

  <tr>
    <td>EKAT_TARGET_SHA</td>
    <td>746968a8a524643787c82b344cfc12f8c18d1a12</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;Packs</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>47</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>EKAT</td>
  </tr>
</table>
</details>


<details>
<summary>
  <b>Console Output (last 100 lines) : EKAT_PullRequest_Autotester_Blake # 65</b> (click to expand)
</summary>
<pre>
<code>
[ 47%] Building CXX object externals/kokkos/core/src/CMakeFiles/kokkoscore.dir/impl/Kokkos_MemoryPool.cpp.o
[ 47%] Building CXX object externals/kokkos/core/src/CMakeFiles/kokkoscore.dir/impl/Kokkos_Spinwait.cpp.o
[ 47%] Building CXX object externals/kokkos/core/src/CMakeFiles/kokkoscore.dir/impl/Kokkos_HostSpace_deepcopy.cpp.o
[ 47%] Building CXX object externals/kokkos/core/src/CMakeFiles/kokkoscore.dir/impl/Kokkos_HostThreadTeam.cpp.o
[ 48%] Building CXX object externals/kokkos/core/src/CMakeFiles/kokkoscore.dir/impl/Kokkos_Serial_Task.cpp.o
[ 48%] Building CXX object externals/kokkos/core/src/CMakeFiles/kokkoscore.dir/impl/Kokkos_hwloc.cpp.o
[ 48%] Building CXX object externals/kokkos/core/src/CMakeFiles/kokkoscore.dir/OpenMP/Kokkos_OpenMP_Exec.cpp.o
[ 48%] Building CXX object externals/kokkos/core/src/CMakeFiles/kokkoscore.dir/impl/Kokkos_Stacktrace.cpp.o
[ 48%] Building CXX object externals/kokkos/core/src/CMakeFiles/kokkoscore.dir/OpenMP/Kokkos_OpenMP_Task.cpp.o
[ 49%] Linking CXX static library libyaml-cppd.a
[ 49%] Built target yaml-cpp
[ 50%] Linking CXX static library libkokkoscore.a
[ 50%] Built target kokkoscore
Scanning dependencies of target kokkoscontainers
[ 51%] Building CXX object externals/kokkos/containers/src/CMakeFiles/kokkoscontainers.dir/impl/Kokkos_UnorderedMap_impl.cpp.o
[ 52%] Linking CXX static library libkokkoscontainers.a
[ 52%] Built target kokkoscontainers
Scanning dependencies of target ekat
[ 53%] Building Fortran object src/ekat/CMakeFiles/ekat.dir/util/ekat_array_io_mod.f90.o
[ 54%] Building CXX object src/ekat/CMakeFiles/ekat.dir/ekat_assert.cpp.o
[ 56%] Building CXX object src/ekat/CMakeFiles/ekat.dir/ekat_parse_yaml_file.cpp.o
[ 56%] Building CXX object src/ekat/CMakeFiles/ekat.dir/ekat_parameter_list.cpp.o
[ 58%] Building CXX object src/ekat/CMakeFiles/ekat.dir/ekat_session.cpp.o
[ 58%] Building CXX object src/ekat/CMakeFiles/ekat.dir/mpi/ekat_comm.cpp.o
[ 62%] Building CXX object src/ekat/CMakeFiles/ekat.dir/util/ekat_arch.cpp.o
[ 62%] Building CXX object src/ekat/CMakeFiles/ekat.dir/util/ekat_array_io.cpp.o
[ 62%] Building CXX object src/ekat/CMakeFiles/ekat.dir/util/ekat_string_utils.cpp.o
[ 62%] Building CXX object src/ekat/CMakeFiles/ekat.dir/util/ekat_test_utils.cpp.o
[ 63%] Linking CXX static library libekat.a
[ 63%] Built target ekat
Scanning dependencies of target ekat_test_session
[ 64%] Building CXX object src/ekat/CMakeFiles/ekat_test_session.dir/util/ekat_test_session.cpp.o
[ 65%] Linking CXX static library libekat_test_session.a
Scanning dependencies of target ekat_test_main
[ 67%] Building CXX object src/ekat/CMakeFiles/ekat_test_main.dir/util/ekat_catch_main.cpp.o
[ 67%] Built target ekat_test_session
Scanning dependencies of target tridiag
[ 68%] Building Fortran object tests/algorithm/CMakeFiles/tridiag.dir/tridiag_bfb_mod.F90.o
[ 71%] Building CXX object tests/algorithm/CMakeFiles/tridiag.dir/tridiag_tests.cpp.o
[ 72%] Building CXX object tests/algorithm/CMakeFiles/tridiag.dir/tridiag_bfb.cpp.o
[ 72%] Building CXX object tests/algorithm/CMakeFiles/tridiag.dir/tridiag_tests_correctness.cpp.o
[ 72%] Building CXX object tests/algorithm/CMakeFiles/tridiag.dir/tridiag_tests_performance.cpp.o
[ 73%] Linking CXX static library libekat_test_main.a
[ 74%] Linking CXX executable tridiag
[ 74%] Built target ekat_test_main
Scanning dependencies of target yaml_parser
Scanning dependencies of target debug_tools
Scanning dependencies of target units
[ 75%] Building CXX object tests/io/CMakeFiles/yaml_parser.dir/yaml_parser.cpp.o
[ 77%] Building CXX object tests/utils/CMakeFiles/debug_tools.dir/debug_tools_tests.cpp.o
[ 77%] Building CXX object tests/units/CMakeFiles/units.dir/units.cpp.o
Scanning dependencies of target lin_interp
Scanning dependencies of target pack_utils
Scanning dependencies of target upper_bound
Scanning dependencies of target util_cxx
Scanning dependencies of target kokkos_utils
Scanning dependencies of target wsm
Scanning dependencies of target packs
Scanning dependencies of target array_io
[ 78%] Building Fortran object tests/algorithm/CMakeFiles/lin_interp.dir/lin_interp_ref.f90.o
[ 80%] Building CXX object tests/utils/CMakeFiles/upper_bound.dir/upper_bound_test.cpp.o
[ 81%] Building CXX object tests/algorithm/CMakeFiles/lin_interp.dir/lin_interp_test.cpp.o
[ 81%] Building CXX object tests/pack/CMakeFiles/pack_utils.dir/pack_utils_tests.cpp.o
[ 83%] Building CXX object tests/utils/CMakeFiles/util_cxx.dir/util_tests.cpp.o
[ 85%] Building CXX object tests/kokkos/CMakeFi [...]

2020-09-22 20:05 UTC, PeterCaldwell commented
Tested on v100 and broadwell (Lassen and quartz). Gave up on testing at cori-knl because it's enviro seems really screwed up. All changes add functionality that shouldn't affect any other lines of code since they are just new (trivially simple) capabilities... so I'm comfortable merging w/out auto-tester.